;              
CREATE USER IF NOT EXISTS "TEST" SALT 'dcdff057432408cc' HASH '70e98ad5228943b6445d968474b32ca0755957cbb4b64a32f444859a9b77a59e' ADMIN;        
CREATE SCHEMA IF NOT EXISTS "SALESMANAGER" AUTHORIZATION "TEST";               
CREATE SEQUENCE "SALESMANAGER"."HIBERNATE_SEQUENCE" START WITH 1;              
CREATE CACHED TABLE "SALESMANAGER"."CATEGORY"(
    "CATEGORY_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CATEGORY_IMAGE" VARCHAR(100),
    "CATEGORY_STATUS" BOOLEAN,
    "CODE" VARCHAR(100) NOT NULL,
    "DEPTH" INTEGER,
    "FEATURED" BOOLEAN,
    "LINEAGE" VARCHAR(255),
    "SORT_ORDER" INTEGER,
    "VISIBLE" BOOLEAN,
    "MERCHANT_ID" INTEGER NOT NULL,
    "PARENT_ID" BIGINT
);          
ALTER TABLE "SALESMANAGER"."CATEGORY" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_3" PRIMARY KEY("CATEGORY_ID"); 
-- 4 +/- SELECT COUNT(*) FROM SALESMANAGER.CATEGORY;           
CREATE CACHED TABLE "SALESMANAGER"."CATEGORY_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "CATEGORY_HIGHLIGHT" VARCHAR(255),
    "META_DESCRIPTION" VARCHAR(255),
    "META_KEYWORDS" VARCHAR(255),
    "META_TITLE" VARCHAR(120),
    "SEF_URL" VARCHAR(120),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CATEGORY_ID" BIGINT NOT NULL
);  
ALTER TABLE "SALESMANAGER"."CATEGORY_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_9" PRIMARY KEY("DESCRIPTION_ID");  
-- 5 +/- SELECT COUNT(*) FROM SALESMANAGER.CATEGORY_DESCRIPTION;               
CREATE CACHED TABLE "SALESMANAGER"."CONTENT"(
    "CONTENT_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CODE" VARCHAR(100) NOT NULL,
    "CONTENT_POSITION" VARCHAR(10),
    "CONTENT_TYPE" VARCHAR(10),
    "LINK_TO_MENU" BOOLEAN,
    "PRODUCT_GROUP" VARCHAR(255),
    "SORT_ORDER" INTEGER,
    "VISIBLE" BOOLEAN,
    "MERCHANT_ID" INTEGER NOT NULL
);             
ALTER TABLE "SALESMANAGER"."CONTENT" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_6" PRIMARY KEY("CONTENT_ID");   
-- 3 +/- SELECT COUNT(*) FROM SALESMANAGER.CONTENT;            
CREATE INDEX "SALESMANAGER"."CODE_IDX" ON "SALESMANAGER"."CONTENT"("CODE");    
CREATE CACHED TABLE "SALESMANAGER"."CONTENT_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "META_DESCRIPTION" VARCHAR(255),
    "META_KEYWORDS" VARCHAR(255),
    "META_TITLE" VARCHAR(255),
    "SEF_URL" VARCHAR(120),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CONTENT_ID" BIGINT NOT NULL
);           
ALTER TABLE "SALESMANAGER"."CONTENT_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_5" PRIMARY KEY("DESCRIPTION_ID");   
-- 5 +/- SELECT COUNT(*) FROM SALESMANAGER.CONTENT_DESCRIPTION;
CREATE CACHED TABLE "SALESMANAGER"."COUNTRY"(
    "COUNTRY_ID" INTEGER NOT NULL,
    "COUNTRY_ISOCODE" VARCHAR(255) NOT NULL,
    "COUNTRY_SUPPORTED" BOOLEAN,
    "GEOZONE_ID" BIGINT
);      
ALTER TABLE "SALESMANAGER"."COUNTRY" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_63" PRIMARY KEY("COUNTRY_ID");  
-- 95 +/- SELECT COUNT(*) FROM SALESMANAGER.COUNTRY;           
CREATE CACHED TABLE "SALESMANAGER"."COUNTRY_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "COUNTRY_ID" INTEGER NOT NULL
);            
ALTER TABLE "SALESMANAGER"."COUNTRY_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_B" PRIMARY KEY("DESCRIPTION_ID");   
-- 190 +/- SELECT COUNT(*) FROM SALESMANAGER.COUNTRY_DESCRIPTION;              
CREATE CACHED TABLE "SALESMANAGER"."CURRENCY"(
    "CURRENCY_ID" BIGINT NOT NULL,
    "CURRENCY_CODE" VARCHAR(255),
    "CURRENCY_CURRENCY_CODE" VARCHAR(255) NOT NULL,
    "CURRENCY_NAME" VARCHAR(255),
    "CURRENCY_SUPPORTED" BOOLEAN
);  
ALTER TABLE "SALESMANAGER"."CURRENCY" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_50" PRIMARY KEY("CURRENCY_ID");
-- 158 +/- SELECT COUNT(*) FROM SALESMANAGER.CURRENCY;         
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER"(
    "CUSTOMER_ID" BIGINT NOT NULL,
    "CUSTOMER_ANONYMOUS" BOOLEAN,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "BILLING_STREET_ADDRESS" VARCHAR(256),
    "BILLING_CITY" VARCHAR(100),
    "BILLING_COMPANY" VARCHAR(100),
    "BILLING_FIRST_NAME" VARCHAR(64) NOT NULL,
    "BILLING_LAST_NAME" VARCHAR(64) NOT NULL,
    "LATITUDE" VARCHAR(100),
    "LONGITUDE" VARCHAR(100),
    "BILLING_POSTCODE" VARCHAR(20),
    "BILLING_STATE" VARCHAR(100),
    "BILLING_TELEPHONE" VARCHAR(32),
    "CUSTOMER_COMPANY" VARCHAR(100),
    "REVIEW_AVG" DECIMAL(19, 2),
    "REVIEW_COUNT" INTEGER,
    "CUSTOMER_DOB" TIMESTAMP,
    "DELIVERY_STREET_ADDRESS" VARCHAR(256),
    "DELIVERY_CITY" VARCHAR(100),
    "DELIVERY_COMPANY" VARCHAR(100),
    "DELIVERY_FIRST_NAME" VARCHAR(64),
    "DELIVERY_LAST_NAME" VARCHAR(64),
    "DELIVERY_POSTCODE" VARCHAR(20),
    "DELIVERY_STATE" VARCHAR(100),
    "DELIVERY_TELEPHONE" VARCHAR(32),
    "CUSTOMER_EMAIL_ADDRESS" VARCHAR(96) NOT NULL,
    "CUSTOMER_GENDER" VARCHAR(1),
    "CUSTOMER_NICK" VARCHAR(96),
    "CUSTOMER_PASSWORD" VARCHAR(60),
    "PROVIDER" VARCHAR(255),
    "BILLING_COUNTRY_ID" INTEGER NOT NULL,
    "BILLING_ZONE_ID" BIGINT,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DELIVERY_COUNTRY_ID" INTEGER,
    "DELIVERY_ZONE_ID" BIGINT,
    "MERCHANT_ID" INTEGER NOT NULL,
    "RESET_CREDENTIALS_REQ" VARCHAR(256),
    "RESET_CREDENTIALS_EXP" DATE
);          
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_52" PRIMARY KEY("CUSTOMER_ID");
-- 3 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER;           
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_ATTRIBUTE"(
    "CUSTOMER_ATTRIBUTE_ID" BIGINT NOT NULL,
    "CUSTOMER_ATTR_TXT_VAL" VARCHAR(255),
    "CUSTOMER_ID" BIGINT NOT NULL,
    "OPTION_ID" BIGINT NOT NULL,
    "OPTION_VALUE_ID" BIGINT NOT NULL
);   
ALTER TABLE "SALESMANAGER"."CUSTOMER_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_5B" PRIMARY KEY("CUSTOMER_ATTRIBUTE_ID");            
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_ATTRIBUTE; 
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_GROUP"(
    "CUSTOMER_ID" BIGINT NOT NULL,
    "GROUP_ID" INTEGER NOT NULL
);     
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_GROUP;     
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_OPT_VAL_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CUSTOMER_OPT_VAL_ID" BIGINT
);    
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPT_VAL_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_BB" PRIMARY KEY("DESCRIPTION_ID");         
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_OPT_VAL_DESCRIPTION;       
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_OPTIN"(
    "CUSTOMER_OPTIN_ID" BIGINT NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "FIRST" VARCHAR(255),
    "LAST" VARCHAR(255),
    "OPTIN_DATE" TIMESTAMP,
    "VALUE" VARCHAR(2147483647),
    "MERCHANT_ID" INTEGER NOT NULL,
    "OPTIN_ID" BIGINT
);  
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTIN" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_3B" PRIMARY KEY("CUSTOMER_OPTIN_ID");    
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_OPTIN;     
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_OPTION"(
    "CUSTOMER_OPTION_ID" BIGINT NOT NULL,
    "CUSTOMER_OPT_ACTIVE" BOOLEAN,
    "CUSTOMER_OPT_CODE" VARCHAR(255),
    "CUSTOMER_OPTION_TYPE" VARCHAR(10),
    "CUSTOMER_OPT_PUBLIC" BOOLEAN,
    "SORT_ORDER" INTEGER,
    "MERCHANT_ID" INTEGER NOT NULL
);            
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_33" PRIMARY KEY("CUSTOMER_OPTION_ID");  
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_OPTION;    
CREATE INDEX "SALESMANAGER"."CUST_OPT_CODE_IDX" ON "SALESMANAGER"."CUSTOMER_OPTION"("CUSTOMER_OPT_CODE");      
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_OPTION_DESC"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "CUSTOMER_OPTION_COMMENT" VARCHAR(2147483647),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CUSTOMER_OPTION_ID" BIGINT NOT NULL
); 
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_DESC" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_4" PRIMARY KEY("DESCRIPTION_ID");  
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_OPTION_DESC;               
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_OPTION_SET"(
    "CUSTOMER_OPTIONSET_ID" BIGINT NOT NULL,
    "SORT_ORDER" INTEGER,
    "CUSTOMER_OPTION_ID" BIGINT NOT NULL,
    "CUSTOMER_OPTION_VALUE_ID" BIGINT NOT NULL
);   
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_SET" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_5D" PRIMARY KEY("CUSTOMER_OPTIONSET_ID");           
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_OPTION_SET;
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_OPTION_VALUE"(
    "CUSTOMER_OPTION_VALUE_ID" BIGINT NOT NULL,
    "CUSTOMER_OPT_VAL_CODE" VARCHAR(255),
    "CUSTOMER_OPT_VAL_IMAGE" VARCHAR(255),
    "SORT_ORDER" INTEGER,
    "MERCHANT_ID" INTEGER NOT NULL
);               
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_VALUE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_5E" PRIMARY KEY("CUSTOMER_OPTION_VALUE_ID");      
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_OPTION_VALUE;              
CREATE INDEX "SALESMANAGER"."CUST_OPT_VAL_CODE_IDX" ON "SALESMANAGER"."CUSTOMER_OPTION_VALUE"("CUSTOMER_OPT_VAL_CODE");        
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_REVIEW"(
    "CUSTOMER_REVIEW_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "REVIEW_DATE" TIMESTAMP,
    "REVIEWS_RATING" DOUBLE,
    "REVIEWS_READ" BIGINT,
    "STATUS" INTEGER,
    "CUSTOMERS_ID" BIGINT,
    "REVIEWED_CUSTOMER_ID" BIGINT
);             
ALTER TABLE "SALESMANAGER"."CUSTOMER_REVIEW" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_38" PRIMARY KEY("CUSTOMER_REVIEW_ID");  
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_REVIEW;    
CREATE CACHED TABLE "SALESMANAGER"."CUSTOMER_REVIEW_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CUSTOMER_REVIEW_ID" BIGINT
);      
ALTER TABLE "SALESMANAGER"."CUSTOMER_REVIEW_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_6D" PRIMARY KEY("DESCRIPTION_ID");          
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CUSTOMER_REVIEW_DESCRIPTION;        
CREATE CACHED TABLE "SALESMANAGER"."FILE_HISTORY"(
    "FILE_HISTORY_ID" BIGINT NOT NULL,
    "ACCOUNTED_DATE" TIMESTAMP,
    "DATE_ADDED" TIMESTAMP NOT NULL,
    "DATE_DELETED" TIMESTAMP,
    "DOWNLOAD_COUNT" INTEGER NOT NULL,
    "FILE_ID" BIGINT,
    "FILESIZE" INTEGER NOT NULL,
    "MERCHANT_ID" INTEGER NOT NULL
);               
ALTER TABLE "SALESMANAGER"."FILE_HISTORY" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_F" PRIMARY KEY("FILE_HISTORY_ID");         
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.FILE_HISTORY;       
CREATE CACHED TABLE "SALESMANAGER"."GEOZONE"(
    "GEOZONE_ID" BIGINT NOT NULL,
    "GEOZONE_CODE" VARCHAR(255),
    "GEOZONE_NAME" VARCHAR(255)
);            
ALTER TABLE "SALESMANAGER"."GEOZONE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_2" PRIMARY KEY("GEOZONE_ID");   
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.GEOZONE;            
CREATE CACHED TABLE "SALESMANAGER"."GEOZONE_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "GEOZONE_ID" BIGINT
);      
ALTER TABLE "SALESMANAGER"."GEOZONE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_1" PRIMARY KEY("DESCRIPTION_ID");   
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.GEOZONE_DESCRIPTION;
CREATE CACHED TABLE "SALESMANAGER"."LANGUAGE"(
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CODE" VARCHAR(255) NOT NULL,
    "SORT_ORDER" INTEGER
);       
ALTER TABLE "SALESMANAGER"."LANGUAGE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_C" PRIMARY KEY("LANGUAGE_ID"); 
-- 2 +/- SELECT COUNT(*) FROM SALESMANAGER.LANGUAGE;           
CREATE INDEX "SALESMANAGER"."CODE_IDX2" ON "SALESMANAGER"."LANGUAGE"("CODE");  
CREATE CACHED TABLE "SALESMANAGER"."MANUFACTURER"(
    "MANUFACTURER_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CODE" VARCHAR(100) NOT NULL,
    "MANUFACTURER_IMAGE" VARCHAR(255),
    "SORT_ORDER" INTEGER,
    "MERCHANT_ID" INTEGER NOT NULL
);     
ALTER TABLE "SALESMANAGER"."MANUFACTURER" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_14" PRIMARY KEY("MANUFACTURER_ID");        
-- 6 +/- SELECT COUNT(*) FROM SALESMANAGER.MANUFACTURER;       
CREATE CACHED TABLE "SALESMANAGER"."MANUFACTURER_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "DATE_LAST_CLICK" TIMESTAMP,
    "MANUFACTURERS_URL" VARCHAR(255),
    "URL_CLICKED" INTEGER,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "MANUFACTURER_ID" BIGINT NOT NULL
); 
ALTER TABLE "SALESMANAGER"."MANUFACTURER_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_2F" PRIMARY KEY("DESCRIPTION_ID");             
-- 6 +/- SELECT COUNT(*) FROM SALESMANAGER.MANUFACTURER_DESCRIPTION;           
CREATE CACHED TABLE "SALESMANAGER"."MERCHANT_CONFIGURATION"(
    "MERCHANT_CONFIG_ID" BIGINT NOT NULL,
    "ACTIVE" BOOLEAN,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CONFIG_KEY" VARCHAR(255),
    "TYPE" VARCHAR(255),
    "VALUE" VARCHAR(2147483647),
    "MERCHANT_ID" INTEGER
);     
ALTER TABLE "SALESMANAGER"."MERCHANT_CONFIGURATION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_D" PRIMARY KEY("MERCHANT_CONFIG_ID");            
-- 7 +/- SELECT COUNT(*) FROM SALESMANAGER.MERCHANT_CONFIGURATION;             
CREATE CACHED TABLE "SALESMANAGER"."MERCHANT_LANGUAGE"(
    "STORES_MERCHANT_ID" INTEGER NOT NULL,
    "LANGUAGES_LANGUAGE_ID" INTEGER NOT NULL
);             
-- 2 +/- SELECT COUNT(*) FROM SALESMANAGER.MERCHANT_LANGUAGE;  
CREATE CACHED TABLE "SALESMANAGER"."MERCHANT_LOG"(
    "MERCHANT_LOG_ID" BIGINT NOT NULL,
    "LOG" VARCHAR(2147483647),
    "MODULE" VARCHAR(25),
    "MERCHANT_ID" INTEGER NOT NULL
);       
ALTER TABLE "SALESMANAGER"."MERCHANT_LOG" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_A" PRIMARY KEY("MERCHANT_LOG_ID");         
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.MERCHANT_LOG;       
CREATE CACHED TABLE "SALESMANAGER"."MERCHANT_STORE"(
    "MERCHANT_ID" INTEGER NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "STORE_CODE" VARCHAR(100) NOT NULL,
    "CONTINUESHOPPINGURL" VARCHAR(150),
    "CURRENCY_FORMAT_NATIONAL" BOOLEAN,
    "DOMAIN_NAME" VARCHAR(80),
    "IN_BUSINESS_SINCE" DATE,
    "INVOICE_TEMPLATE" VARCHAR(25),
    "SEIZEUNITCODE" VARCHAR(5),
    "STORE_EMAIL" VARCHAR(60) NOT NULL,
    "STORE_LOGO" VARCHAR(100),
    "STORE_TEMPLATE" VARCHAR(25),
    "STORE_ADDRESS" VARCHAR(255),
    "STORE_CITY" VARCHAR(100),
    "STORE_NAME" VARCHAR(100) NOT NULL,
    "STORE_PHONE" VARCHAR(50),
    "STORE_POSTAL_CODE" VARCHAR(15),
    "STORE_STATE_PROV" VARCHAR(100),
    "USE_CACHE" BOOLEAN,
    "WEIGHTUNITCODE" VARCHAR(5),
    "COUNTRY_ID" INTEGER NOT NULL,
    "CURRENCY_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "ZONE_ID" BIGINT,
    "IS_RETAILER" BOOLEAN,
    "PARENT_ID" INTEGER
);           
ALTER TABLE "SALESMANAGER"."MERCHANT_STORE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_AA" PRIMARY KEY("MERCHANT_ID");          
-- 1 +/- SELECT COUNT(*) FROM SALESMANAGER.MERCHANT_STORE;     
CREATE CACHED TABLE "SALESMANAGER"."MODULE_CONFIGURATION"(
    "MODULE_CONF_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CODE" VARCHAR(255) NOT NULL,
    "DETAILS" VARCHAR(2147483647),
    "CONFIGURATION" VARCHAR(2147483647),
    "CUSTOM_IND" BOOLEAN,
    "IMAGE" VARCHAR(255),
    "MODULE" VARCHAR(255),
    "REGIONS" VARCHAR(255),
    "TYPE" VARCHAR(255)
);   
ALTER TABLE "SALESMANAGER"."MODULE_CONFIGURATION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_501" PRIMARY KEY("MODULE_CONF_ID");
-- 12 +/- SELECT COUNT(*) FROM SALESMANAGER.MODULE_CONFIGURATION;              
CREATE INDEX "SALESMANAGER"."MODULE_CONFIGURATION_MODULE" ON "SALESMANAGER"."MODULE_CONFIGURATION"("MODULE");  
CREATE CACHED TABLE "SALESMANAGER"."OPTIN"(
    "OPTIN_ID" BIGINT NOT NULL,
    "CODE" VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "END_DATE" TIMESTAMP,
    "TYPE" VARCHAR(255) NOT NULL,
    "START_DATE" TIMESTAMP,
    "MERCHANT_ID" INTEGER
);             
ALTER TABLE "SALESMANAGER"."OPTIN" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_47" PRIMARY KEY("OPTIN_ID");      
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.OPTIN;              
CREATE CACHED TABLE "SALESMANAGER"."ORDER_ACCOUNT"(
    "ORDER_ACCOUNT_ID" BIGINT NOT NULL,
    "ORDER_ACCOUNT_BILL_DAY" INTEGER NOT NULL,
    "ORDER_ACCOUNT_END_DATE" DATE,
    "ORDER_ACCOUNT_START_DATE" DATE NOT NULL,
    "ORDER_ID" BIGINT NOT NULL
);  
ALTER TABLE "SALESMANAGER"."ORDER_ACCOUNT" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_64" PRIMARY KEY("ORDER_ACCOUNT_ID");      
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_ACCOUNT;      
CREATE CACHED TABLE "SALESMANAGER"."ORDER_ACCOUNT_PRODUCT"(
    "ORDER_ACCOUNT_PRODUCT_ID" BIGINT NOT NULL,
    "ORDER_ACCOUNT_PRODUCT_ACCNT_DT" DATE,
    "ORDER_ACCOUNT_PRODUCT_END_DT" DATE,
    "ORDER_ACCOUNT_PRODUCT_EOT" TIMESTAMP,
    "ORDER_ACCOUNT_PRODUCT_L_ST_DT" TIMESTAMP,
    "ORDER_ACCOUNT_PRODUCT_L_TRX_ST" INTEGER NOT NULL,
    "ORDER_ACCOUNT_PRODUCT_PM_FR_TY" INTEGER NOT NULL,
    "ORDER_ACCOUNT_PRODUCT_ST_DT" DATE NOT NULL,
    "ORDER_ACCOUNT_PRODUCT_STATUS" INTEGER NOT NULL,
    "ORDER_ACCOUNT_ID" BIGINT NOT NULL,
    "ORDER_PRODUCT_ID" BIGINT NOT NULL
);
ALTER TABLE "SALESMANAGER"."ORDER_ACCOUNT_PRODUCT" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_20" PRIMARY KEY("ORDER_ACCOUNT_PRODUCT_ID");      
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_ACCOUNT_PRODUCT;              
CREATE CACHED TABLE "SALESMANAGER"."ORDER_ATTRIBUTE"(
    "ORDER_ATTRIBUTE_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(255) NOT NULL,
    "VALUE" VARCHAR(255) NOT NULL,
    "ORDER_ID" BIGINT NOT NULL
);   
ALTER TABLE "SALESMANAGER"."ORDER_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_8" PRIMARY KEY("ORDER_ATTRIBUTE_ID");   
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_ATTRIBUTE;    
CREATE CACHED TABLE "SALESMANAGER"."ORDER_PRODUCT"(
    "ORDER_PRODUCT_ID" BIGINT NOT NULL,
    "ONETIME_CHARGE" DECIMAL(19, 2) NOT NULL,
    "PRODUCT_NAME" VARCHAR(64) NOT NULL,
    "PRODUCT_QUANTITY" INTEGER,
    "PRODUCT_SKU" VARCHAR(255),
    "ORDER_ID" BIGINT NOT NULL
);           
ALTER TABLE "SALESMANAGER"."ORDER_PRODUCT" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_98" PRIMARY KEY("ORDER_PRODUCT_ID");      
-- 3 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_PRODUCT;      
CREATE CACHED TABLE "SALESMANAGER"."ORDER_PRODUCT_ATTRIBUTE"(
    "ORDER_PRODUCT_ATTRIBUTE_ID" BIGINT NOT NULL,
    "PRODUCT_ATTRIBUTE_IS_FREE" BOOLEAN NOT NULL,
    "PRODUCT_ATTRIBUTE_NAME" VARCHAR(255),
    "PRODUCT_ATTRIBUTE_PRICE" DECIMAL(15, 4) NOT NULL,
    "PRODUCT_ATTRIBUTE_VAL_NAME" VARCHAR(255),
    "PRODUCT_ATTRIBUTE_WEIGHT" DECIMAL(15, 4),
    "PRODUCT_OPTION_ID" BIGINT NOT NULL,
    "PRODUCT_OPTION_VALUE_ID" BIGINT NOT NULL,
    "ORDER_PRODUCT_ID" BIGINT NOT NULL
);            
ALTER TABLE "SALESMANAGER"."ORDER_PRODUCT_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_23" PRIMARY KEY("ORDER_PRODUCT_ATTRIBUTE_ID");  
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_PRODUCT_ATTRIBUTE;            
CREATE CACHED TABLE "SALESMANAGER"."ORDER_PRODUCT_DOWNLOAD"(
    "ORDER_PRODUCT_DOWNLOAD_ID" BIGINT NOT NULL,
    "DOWNLOAD_COUNT" INTEGER NOT NULL,
    "DOWNLOAD_MAXDAYS" INTEGER NOT NULL,
    "ORDER_PRODUCT_FILENAME" VARCHAR(255) NOT NULL,
    "ORDER_PRODUCT_ID" BIGINT NOT NULL
);    
ALTER TABLE "SALESMANAGER"."ORDER_PRODUCT_DOWNLOAD" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_F3" PRIMARY KEY("ORDER_PRODUCT_DOWNLOAD_ID");    
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_PRODUCT_DOWNLOAD;             
CREATE CACHED TABLE "SALESMANAGER"."ORDER_PRODUCT_PRICE"(
    "ORDER_PRODUCT_PRICE_ID" BIGINT NOT NULL,
    "DEFAULT_PRICE" BOOLEAN NOT NULL,
    "PRODUCT_PRICE" DECIMAL(19, 2) NOT NULL,
    "PRODUCT_PRICE_CODE" VARCHAR(64) NOT NULL,
    "PRODUCT_PRICE_NAME" VARCHAR(255),
    "PRODUCT_PRICE_SPECIAL" DECIMAL(19, 2),
    "PRD_PRICE_SPECIAL_END_DT" TIMESTAMP,
    "PRD_PRICE_SPECIAL_ST_DT" TIMESTAMP,
    "ORDER_PRODUCT_ID" BIGINT NOT NULL
);      
ALTER TABLE "SALESMANAGER"."ORDER_PRODUCT_PRICE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_84" PRIMARY KEY("ORDER_PRODUCT_PRICE_ID");          
-- 3 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_PRODUCT_PRICE;
CREATE CACHED TABLE "SALESMANAGER"."ORDER_STATUS_HISTORY"(
    "ORDER_STATUS_HISTORY_ID" BIGINT NOT NULL,
    "COMMENTS" VARCHAR(2147483647),
    "CUSTOMER_NOTIFIED" INTEGER,
    "DATE_ADDED" TIMESTAMP NOT NULL,
    "STATUS" VARCHAR(255),
    "ORDER_ID" BIGINT NOT NULL
);               
ALTER TABLE "SALESMANAGER"."ORDER_STATUS_HISTORY" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_53" PRIMARY KEY("ORDER_STATUS_HISTORY_ID");        
-- 3 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_STATUS_HISTORY;               
CREATE CACHED TABLE "SALESMANAGER"."ORDER_TOTAL"(
    "ORDER_ACCOUNT_ID" BIGINT NOT NULL,
    "MODULE" VARCHAR(60),
    "CODE" VARCHAR(255) NOT NULL,
    "ORDER_TOTAL_TYPE" VARCHAR(255),
    "ORDER_VALUE_TYPE" VARCHAR(255),
    "SORT_ORDER" INTEGER NOT NULL,
    "TEXT" VARCHAR(2147483647),
    "TITLE" VARCHAR(255),
    "VALUE" DECIMAL(15, 4) NOT NULL,
    "ORDER_ID" BIGINT NOT NULL
);            
ALTER TABLE "SALESMANAGER"."ORDER_TOTAL" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_2C" PRIMARY KEY("ORDER_ACCOUNT_ID");        
-- 9 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDER_TOTAL;        
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_OPT_SET_OPT_VALUE"(
    "PRODUCTOPTIONSET_PRODUCT_OPTION_SET_ID" BIGINT NOT NULL,
    "VALUES_PRODUCT_OPTION_VALUE_ID" BIGINT NOT NULL
);          
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_OPT_SET_OPT_VALUE;          
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_OPTION_SET"(
    "PRODUCT_OPTION_SET_ID" BIGINT NOT NULL,
    "PRODUCT_OPTION_SET_CODE" VARCHAR(255),
    "PRODUCT_OPTION_SET_DISP" BOOLEAN,
    "PRODUCT_OPTION_ID" BIGINT NOT NULL,
    "MERCHANT_ID" INTEGER NOT NULL
);        
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_SET" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_5F3" PRIMARY KEY("PRODUCT_OPTION_SET_ID");           
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_OPTION_SET; 
CREATE CACHED TABLE "SALESMANAGER"."PERMISSION"(
    "PERMISSION_ID" INTEGER NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "PERMISSION_NAME" VARCHAR(255)
);           
ALTER TABLE "SALESMANAGER"."PERMISSION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_FE" PRIMARY KEY("PERMISSION_ID");            
-- 13 +/- SELECT COUNT(*) FROM SALESMANAGER.PERMISSION;        
CREATE CACHED TABLE "SALESMANAGER"."PERMISSION_GROUP"(
    "PERMISSION_ID" INTEGER NOT NULL,
    "GROUP_ID" INTEGER NOT NULL
);
-- 35 +/- SELECT COUNT(*) FROM SALESMANAGER.PERMISSION_GROUP;  
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT"(
    "PRODUCT_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "AVAILABLE" BOOLEAN,
    "COND" INTEGER,
    "DATE_AVAILABLE" TIMESTAMP,
    "PREORDER" BOOLEAN,
    "PRODUCT_HEIGHT" DECIMAL(19, 2),
    "PRODUCT_FREE" BOOLEAN,
    "PRODUCT_LENGTH" DECIMAL(19, 2),
    "QUANTITY_ORDERED" INTEGER,
    "REVIEW_AVG" DECIMAL(19, 2),
    "REVIEW_COUNT" INTEGER,
    "PRODUCT_SHIP" BOOLEAN,
    "PRODUCT_VIRTUAL" BOOLEAN,
    "PRODUCT_WEIGHT" DECIMAL(19, 2),
    "PRODUCT_WIDTH" DECIMAL(19, 2),
    "REF_SKU" VARCHAR(255),
    "RENTAL_DURATION" INTEGER,
    "RENTAL_PERIOD" INTEGER,
    "RENTAL_STATUS" INTEGER,
    "SKU" VARCHAR(255),
    "SORT_ORDER" INTEGER,
    "MANUFACTURER_ID" BIGINT,
    "MERCHANT_ID" INTEGER NOT NULL,
    "CUSTOMER_ID" BIGINT,
    "TAX_CLASS_ID" BIGINT,
    "PRODUCT_TYPE_ID" BIGINT
);              
ALTER TABLE "SALESMANAGER"."PRODUCT" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_18" PRIMARY KEY("PRODUCT_ID");  
-- 10 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT;           
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_ATTRIBUTE"(
    "PRODUCT_ATTRIBUTE_ID" BIGINT NOT NULL,
    "PRODUCT_ATTRIBUTE_DEFAULT" BOOLEAN,
    "PRODUCT_ATTRIBUTE_DISCOUNTED" BOOLEAN,
    "PRODUCT_ATTRIBUTE_FOR_DISP" BOOLEAN,
    "PRODUCT_ATTRIBUTE_REQUIRED" BOOLEAN,
    "PRODUCT_ATTRIBUTE_FREE" BOOLEAN,
    "PRODUCT_ATRIBUTE_PRICE" DECIMAL(19, 2),
    "PRODUCT_ATTRIBUTE_WEIGHT" DECIMAL(19, 2),
    "PRODUCT_ATTRIBUTE_SORT_ORD" INTEGER,
    "PRODUCT_ID" BIGINT NOT NULL,
    "OPTION_ID" BIGINT NOT NULL,
    "OPTION_VALUE_ID" BIGINT NOT NULL
);           
ALTER TABLE "SALESMANAGER"."PRODUCT_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_8D" PRIMARY KEY("PRODUCT_ATTRIBUTE_ID");              
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_ATTRIBUTE;  
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_TYPE"(
    "PRODUCT_TYPE_ID" BIGINT NOT NULL,
    "PRD_TYPE_ADD_TO_CART" BOOLEAN,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "PRD_TYPE_CODE" VARCHAR(255),
    "MERCHANT_ID" INTEGER,
    "PRD_TYPE_VISIBLE" BOOLEAN
);           
ALTER TABLE "SALESMANAGER"."PRODUCT_TYPE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_C8" PRIMARY KEY("PRODUCT_TYPE_ID");        
-- 1 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_TYPE;       
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_CATEGORY"(
    "PRODUCT_ID" BIGINT NOT NULL,
    "CATEGORY_ID" BIGINT NOT NULL
);  
ALTER TABLE "SALESMANAGER"."PRODUCT_CATEGORY" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_39" PRIMARY KEY("PRODUCT_ID", "CATEGORY_ID");          
-- 10 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_CATEGORY;  
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "META_DESCRIPTION" VARCHAR(255),
    "META_KEYWORDS" VARCHAR(255),
    "META_TITLE" VARCHAR(255),
    "DOWNLOAD_LNK" VARCHAR(255),
    "PRODUCT_HIGHLIGHT" VARCHAR(255),
    "SEF_URL" VARCHAR(255),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL
);    
ALTER TABLE "SALESMANAGER"."PRODUCT_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_35" PRIMARY KEY("DESCRIPTION_ID");  
-- 20 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_DESCRIPTION;               
CREATE INDEX "SALESMANAGER"."PRODUCT_DESCRIPTION_SEF_URL" ON "SALESMANAGER"."PRODUCT_DESCRIPTION"("SEF_URL");  
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_DIGITAL"(
    "PRODUCT_DIGITAL_ID" BIGINT NOT NULL,
    "FILE_NAME" VARCHAR(255) NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL
);     
ALTER TABLE "SALESMANAGER"."PRODUCT_DIGITAL" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_332" PRIMARY KEY("PRODUCT_DIGITAL_ID"); 
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_DIGITAL;    
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_IMAGE_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "ALT_TAG" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "PRODUCT_IMAGE_ID" BIGINT NOT NULL
);     
ALTER TABLE "SALESMANAGER"."PRODUCT_IMAGE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_7" PRIMARY KEY("DESCRIPTION_ID");             
-- 20 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_IMAGE_DESCRIPTION;         
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_OPTION"(
    "PRODUCT_OPTION_ID" BIGINT NOT NULL,
    "PRODUCT_OPTION_CODE" VARCHAR(255),
    "PRODUCT_OPTION_SORT_ORD" INTEGER,
    "PRODUCT_OPTION_TYPE" VARCHAR(10),
    "PRODUCT_OPTION_READ" BOOLEAN,
    "MERCHANT_ID" INTEGER NOT NULL
);   
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_14D" PRIMARY KEY("PRODUCT_OPTION_ID");   
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_OPTION;     
CREATE INDEX "SALESMANAGER"."PRD_OPTION_CODE_IDX" ON "SALESMANAGER"."PRODUCT_OPTION"("PRODUCT_OPTION_CODE");   
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_OPTION_DESC"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "PRODUCT_OPTION_COMMENT" VARCHAR(2147483647),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "PRODUCT_OPTION_ID" BIGINT NOT NULL
);    
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_DESC" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_88" PRIMARY KEY("DESCRIPTION_ID");  
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_OPTION_DESC;
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE"(
    "PRODUCT_OPTION_VALUE_ID" BIGINT NOT NULL,
    "PRODUCT_OPTION_VAL_CODE" VARCHAR(255),
    "PRODUCT_OPT_FOR_DISP" BOOLEAN,
    "PRODUCT_OPT_VAL_IMAGE" VARCHAR(255),
    "PRODUCT_OPT_VAL_SORT_ORD" INTEGER,
    "MERCHANT_ID" INTEGER NOT NULL
);              
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_8D0" PRIMARY KEY("PRODUCT_OPTION_VALUE_ID");       
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_OPTION_VALUE;               
CREATE INDEX "SALESMANAGER"."PRD_OPTION_VAL_CODE_IDX" ON "SALESMANAGER"."PRODUCT_OPTION_VALUE"("PRODUCT_OPTION_VAL_CODE");     
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "PRODUCT_OPTION_VALUE_ID" BIGINT
);            
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_1E" PRIMARY KEY("DESCRIPTION_ID");     
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_OPTION_VALUE_DESCRIPTION;   
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_PRICE"(
    "PRODUCT_PRICE_ID" BIGINT NOT NULL,
    "PRODUCT_PRICE_CODE" VARCHAR(255) NOT NULL,
    "DEFAULT_PRICE" BOOLEAN,
    "PRODUCT_PRICE_AMOUNT" DECIMAL(19, 2) NOT NULL,
    "PRODUCT_PRICE_SPECIAL_AMOUNT" DECIMAL(19, 2),
    "PRODUCT_PRICE_SPECIAL_END_DATE" DATE,
    "PRODUCT_PRICE_SPECIAL_ST_DATE" DATE,
    "PRODUCT_PRICE_TYPE" VARCHAR(20),
    "PRODUCT_AVAIL_ID" BIGINT NOT NULL
);           
ALTER TABLE "SALESMANAGER"."PRODUCT_PRICE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_42C" PRIMARY KEY("PRODUCT_PRICE_ID");     
-- 10 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_PRICE;     
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_VARIANT"(
    "PRODUCT_VARIANT_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(60),
    "PRODUCT_AQUANTITY" INTEGER,
    "PRODUCT_ATTRIBUTE_ID" BIGINT NOT NULL,
    "PRODUCT_AVAIL_ID" BIGINT NOT NULL
); 
ALTER TABLE "SALESMANAGER"."PRODUCT_VARIANT" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_DE" PRIMARY KEY("PRODUCT_VARIANT_ID");  
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_VARIANT;    
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_RELATIONSHIP"(
    "PRODUCT_RELATIONSHIP_ID" BIGINT NOT NULL,
    "ACTIVE" BOOLEAN,
    "CODE" VARCHAR(255),
    "PRODUCT_ID" BIGINT,
    "RELATED_PRODUCT_ID" BIGINT,
    "MERCHANT_ID" INTEGER NOT NULL
);       
ALTER TABLE "SALESMANAGER"."PRODUCT_RELATIONSHIP" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_DD" PRIMARY KEY("PRODUCT_RELATIONSHIP_ID");        
-- 4 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_RELATIONSHIP;               
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_REVIEW"(
    "PRODUCT_REVIEW_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "REVIEW_DATE" TIMESTAMP,
    "REVIEWS_RATING" DOUBLE,
    "REVIEWS_READ" BIGINT,
    "STATUS" INTEGER,
    "CUSTOMERS_ID" BIGINT,
    "PRODUCT_ID" BIGINT
);         
ALTER TABLE "SALESMANAGER"."PRODUCT_REVIEW" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_19" PRIMARY KEY("PRODUCT_REVIEW_ID");    
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_REVIEW;     
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_REVIEW_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "PRODUCT_REVIEW_ID" BIGINT
);        
ALTER TABLE "SALESMANAGER"."PRODUCT_REVIEW_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_AD" PRIMARY KEY("DESCRIPTION_ID");           
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_REVIEW_DESCRIPTION;         
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_TYPE_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "PRODUCT_TYPE_ID" BIGINT NOT NULL
);   
ALTER TABLE "SALESMANAGER"."PRODUCT_TYPE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_9F" PRIMARY KEY("DESCRIPTION_ID");             
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_TYPE_DESCRIPTION;           
CREATE CACHED TABLE "SALESMANAGER"."SHIPING_ORIGIN"(
    "SHIP_ORIGIN_ID" BIGINT NOT NULL,
    "ACTIVE" BOOLEAN,
    "STREET_ADDRESS" VARCHAR(256),
    "CITY" VARCHAR(100),
    "POSTCODE" VARCHAR(20),
    "STATE" VARCHAR(100),
    "COUNTRY_ID" INTEGER,
    "MERCHANT_ID" INTEGER NOT NULL,
    "ZONE_ID" BIGINT
);       
ALTER TABLE "SALESMANAGER"."SHIPING_ORIGIN" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_DB" PRIMARY KEY("SHIP_ORIGIN_ID");       
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.SHIPING_ORIGIN;     
CREATE CACHED TABLE "SALESMANAGER"."SHOPPING_CART"(
    "SHP_CART_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CUSTOMER_ID" BIGINT,
    "SHP_CART_CODE" VARCHAR(255) NOT NULL,
    "MERCHANT_ID" INTEGER NOT NULL,
    "IP_ADDRESS" VARCHAR(255),
    "ORDER_ID" BIGINT,
    "PROMO_ADDED" TIMESTAMP,
    "PROMO_CODE" VARCHAR(255)
);    
ALTER TABLE "SALESMANAGER"."SHOPPING_CART" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_59" PRIMARY KEY("SHP_CART_ID");           
-- 12 +/- SELECT COUNT(*) FROM SALESMANAGER.SHOPPING_CART;     
CREATE INDEX "SALESMANAGER"."SHP_CART_CODE_IDX" ON "SALESMANAGER"."SHOPPING_CART"("SHP_CART_CODE");            
CREATE INDEX "SALESMANAGER"."SHP_CART_CUSTOMER_IDX" ON "SALESMANAGER"."SHOPPING_CART"("CUSTOMER_ID");          
CREATE CACHED TABLE "SALESMANAGER"."SHOPPING_CART_ATTR_ITEM"(
    "SHP_CART_ATTR_ITEM_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "PRODUCT_ATTR_ID" BIGINT NOT NULL,
    "SHP_CART_ITEM_ID" BIGINT NOT NULL
);            
ALTER TABLE "SALESMANAGER"."SHOPPING_CART_ATTR_ITEM" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_45" PRIMARY KEY("SHP_CART_ATTR_ITEM_ID");       
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.SHOPPING_CART_ATTR_ITEM;            
CREATE CACHED TABLE "SALESMANAGER"."SHOPPING_CART_ITEM"(
    "SHP_CART_ITEM_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "PRODUCT_ID" BIGINT NOT NULL,
    "QUANTITY" INTEGER,
    "SHP_CART_ID" BIGINT NOT NULL
);        
ALTER TABLE "SALESMANAGER"."SHOPPING_CART_ITEM" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_B3" PRIMARY KEY("SHP_CART_ITEM_ID"); 
-- 11 +/- SELECT COUNT(*) FROM SALESMANAGER.SHOPPING_CART_ITEM;
CREATE CACHED TABLE "SALESMANAGER"."SM_GROUP"(
    "GROUP_ID" INTEGER NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "GROUP_NAME" VARCHAR(255),
    "GROUP_TYPE" VARCHAR(255)
);        
ALTER TABLE "SALESMANAGER"."SM_GROUP" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_3D" PRIMARY KEY("GROUP_ID");   
-- 7 +/- SELECT COUNT(*) FROM SALESMANAGER.SM_GROUP;           
CREATE INDEX "SALESMANAGER"."SM_GROUP_GROUP_TYPE" ON "SALESMANAGER"."SM_GROUP"("GROUP_TYPE");  
CREATE CACHED TABLE "SALESMANAGER"."SM_SEQUENCER"(
    "SEQ_NAME" VARCHAR(255) NOT NULL,
    "SEQ_COUNT" BIGINT
);             
ALTER TABLE "SALESMANAGER"."SM_SEQUENCER" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_525" PRIMARY KEY("SEQ_NAME");              
-- 31 +/- SELECT COUNT(*) FROM SALESMANAGER.SM_SEQUENCER;      
CREATE CACHED TABLE "SALESMANAGER"."SM_TRANSACTION"(
    "TRANSACTION_ID" BIGINT NOT NULL,
    "AMOUNT" DECIMAL(19, 2),
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DETAILS" VARCHAR(2147483647),
    "PAYMENT_TYPE" VARCHAR(255),
    "TRANSACTION_DATE" TIMESTAMP,
    "TRANSACTION_TYPE" VARCHAR(255),
    "ORDER_ID" BIGINT
);            
ALTER TABLE "SALESMANAGER"."SM_TRANSACTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_D3" PRIMARY KEY("TRANSACTION_ID");       
-- 3 +/- SELECT COUNT(*) FROM SALESMANAGER.SM_TRANSACTION;     
CREATE CACHED TABLE "SALESMANAGER"."SYSTEM_CONFIGURATION"(
    "SYSTEM_CONFIG_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CONFIG_KEY" VARCHAR(255),
    "VALUE" VARCHAR(255)
);          
ALTER TABLE "SALESMANAGER"."SYSTEM_CONFIGURATION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_9E" PRIMARY KEY("SYSTEM_CONFIG_ID");               
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.SYSTEM_CONFIGURATION;               
CREATE CACHED TABLE "SALESMANAGER"."SYSTEM_NOTIFICATION"(
    "SYSTEM_NOTIF_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "END_DATE" DATE,
    "CONFIG_KEY" VARCHAR(255),
    "START_DATE" DATE,
    "VALUE" VARCHAR(255),
    "MERCHANT_ID" INTEGER,
    "USER_ID" BIGINT
);               
ALTER TABLE "SALESMANAGER"."SYSTEM_NOTIFICATION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_87" PRIMARY KEY("SYSTEM_NOTIF_ID"); 
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.SYSTEM_NOTIFICATION;
CREATE CACHED TABLE "SALESMANAGER"."TAX_CLASS"(
    "TAX_CLASS_ID" BIGINT NOT NULL,
    "TAX_CLASS_CODE" VARCHAR(10) NOT NULL,
    "TAX_CLASS_TITLE" VARCHAR(32) NOT NULL,
    "MERCHANT_ID" INTEGER
);        
ALTER TABLE "SALESMANAGER"."TAX_CLASS" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_DBB" PRIMARY KEY("TAX_CLASS_ID");             
-- 1 +/- SELECT COUNT(*) FROM SALESMANAGER.TAX_CLASS;          
CREATE INDEX "SALESMANAGER"."TAX_CLASS_CODE_IDX" ON "SALESMANAGER"."TAX_CLASS"("TAX_CLASS_CODE");              
CREATE CACHED TABLE "SALESMANAGER"."TAX_RATE"(
    "TAX_RATE_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "TAX_CODE" VARCHAR(255),
    "PIGGYBACK" BOOLEAN,
    "STORE_STATE_PROV" VARCHAR(100),
    "TAX_PRIORITY" INTEGER,
    "TAX_RATE" DECIMAL(7, 4) NOT NULL,
    "COUNTRY_ID" INTEGER NOT NULL,
    "MERCHANT_ID" INTEGER NOT NULL,
    "PARENT_ID" BIGINT,
    "TAX_CLASS_ID" BIGINT NOT NULL,
    "ZONE_ID" BIGINT
);             
ALTER TABLE "SALESMANAGER"."TAX_RATE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_1F" PRIMARY KEY("TAX_RATE_ID");
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.TAX_RATE;           
CREATE CACHED TABLE "SALESMANAGER"."TAX_RATE_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "TAX_RATE_ID" BIGINT
);    
ALTER TABLE "SALESMANAGER"."TAX_RATE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_26" PRIMARY KEY("DESCRIPTION_ID"); 
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.TAX_RATE_DESCRIPTION;               
CREATE CACHED TABLE "SALESMANAGER"."USERS"(
    "USER_ID" BIGINT NOT NULL,
    "ACTIVE" BOOLEAN,
    "ADMIN_EMAIL" VARCHAR(255),
    "ADMIN_NAME" VARCHAR(100),
    "ADMIN_PASSWORD" VARCHAR(60),
    "ADMIN_A1" VARCHAR(255),
    "ADMIN_A2" VARCHAR(255),
    "ADMIN_A3" VARCHAR(255),
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "ADMIN_FIRST_NAME" VARCHAR(255),
    "LAST_ACCESS" TIMESTAMP,
    "ADMIN_LAST_NAME" VARCHAR(255),
    "LOGIN_ACCESS" TIMESTAMP,
    "ADMIN_Q1" VARCHAR(255),
    "ADMIN_Q2" VARCHAR(255),
    "ADMIN_Q3" VARCHAR(255),
    "LANGUAGE_ID" INTEGER,
    "MERCHANT_ID" INTEGER NOT NULL,
    "PASSWORD_TOKEN" VARCHAR(255),
    "EXPIRED_P_TOKEN" TIMESTAMP,
    "RESET_CREDENTIALS_REQ" VARCHAR(256),
    "RESET_CREDENTIALS_EXP" DATE
);   
ALTER TABLE "SALESMANAGER"."USERS" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_27" PRIMARY KEY("USER_ID");       
-- 2 +/- SELECT COUNT(*) FROM SALESMANAGER.USERS;              
CREATE CACHED TABLE "SALESMANAGER"."USER_GROUP"(
    "USER_ID" BIGINT NOT NULL,
    "GROUP_ID" INTEGER NOT NULL
);             
-- 3 +/- SELECT COUNT(*) FROM SALESMANAGER.USER_GROUP;         
CREATE CACHED TABLE "SALESMANAGER"."USERCONNECTION"(
    "PROVIDERID" VARCHAR(255) NOT NULL,
    "PROVIDERUSERID" VARCHAR(255) NOT NULL,
    "USERID" VARCHAR(255) NOT NULL,
    "ACCESSTOKEN" VARCHAR(255),
    "DISPLAYNAME" VARCHAR(255),
    "EXPIRETIME" BIGINT,
    "IMAGEURL" VARCHAR(255),
    "PROFILEURL" VARCHAR(255),
    "REFRESHTOKEN" VARCHAR(255),
    "SECRET" VARCHAR(255),
    "USERRANK" INTEGER NOT NULL
);               
ALTER TABLE "SALESMANAGER"."USERCONNECTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_5F" PRIMARY KEY("PROVIDERID", "PROVIDERUSERID", "USERID");               
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.USERCONNECTION;     
CREATE CACHED TABLE "SALESMANAGER"."ZONE"(
    "ZONE_ID" BIGINT NOT NULL,
    "ZONE_CODE" VARCHAR(255) NOT NULL,
    "COUNTRY_ID" INTEGER NOT NULL
);          
ALTER TABLE "SALESMANAGER"."ZONE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_2A" PRIMARY KEY("ZONE_ID");        
-- 189 +/- SELECT COUNT(*) FROM SALESMANAGER.ZONE;             
CREATE CACHED TABLE "SALESMANAGER"."ZONE_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "ZONE_ID" BIGINT NOT NULL
);   
ALTER TABLE "SALESMANAGER"."ZONE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_17" PRIMARY KEY("DESCRIPTION_ID");     
-- 376 +/- SELECT COUNT(*) FROM SALESMANAGER.ZONE_DESCRIPTION; 
CREATE CACHED TABLE "SALESMANAGER"."SHIPPING_QUOTE"(
    "SHIPPING_QUOTE_ID" BIGINT NOT NULL,
    "CART_ID" BIGINT,
    "CUSTOMER_ID" BIGINT,
    "DELIVERY_STREET_ADDRESS" VARCHAR(256),
    "DELIVERY_CITY" VARCHAR(100),
    "DELIVERY_COMPANY" VARCHAR(100),
    "DELIVERY_FIRST_NAME" VARCHAR(64),
    "DELIVERY_LAST_NAME" VARCHAR(64),
    "DELIVERY_POSTCODE" VARCHAR(20),
    "DELIVERY_STATE" VARCHAR(100),
    "DELIVERY_TELEPHONE" VARCHAR(32),
    "SHIPPING_NUMBER_DAYS" INTEGER,
    "FREE_SHIPPING" BOOLEAN,
    "QUOTE_HANDLING" DECIMAL(19, 2),
    "MODULE" VARCHAR(255) NOT NULL,
    "OPTION_CODE" VARCHAR(255),
    "OPTION_DELIVERY_DATE" TIMESTAMP,
    "OPTION_NAME" VARCHAR(255),
    "OPTION_SHIPPING_DATE" TIMESTAMP,
    "ORDER_ID" BIGINT,
    "QUOTE_PRICE" DECIMAL(19, 2),
    "QUOTE_DATE" TIMESTAMP,
    "DELIVERY_COUNTRY_ID" INTEGER,
    "DELIVERY_ZONE_ID" BIGINT,
    "IP_ADDRESS" VARCHAR(255)
);      
ALTER TABLE "SALESMANAGER"."SHIPPING_QUOTE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_A0" PRIMARY KEY("SHIPPING_QUOTE_ID");    
-- 49 +/- SELECT COUNT(*) FROM SALESMANAGER.SHIPPING_QUOTE;    
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_PRICE_DESCRIPTION"(
    "DESCRIPTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "DESCRIPTION" VARCHAR(2147483647),
    "NAME" VARCHAR(120) NOT NULL,
    "TITLE" VARCHAR(100),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "PRODUCT_PRICE_ID" BIGINT NOT NULL,
    "PRICE_APPENDER" VARCHAR(255)
);              
ALTER TABLE "SALESMANAGER"."PRODUCT_PRICE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_54" PRIMARY KEY("DESCRIPTION_ID");            
-- 20 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_PRICE_DESCRIPTION;         
CREATE CACHED TABLE "SALESMANAGER"."ORDERS"(
    "ORDER_ID" BIGINT NOT NULL,
    "BILLING_STREET_ADDRESS" VARCHAR(256),
    "BILLING_CITY" VARCHAR(100),
    "BILLING_COMPANY" VARCHAR(100),
    "BILLING_FIRST_NAME" VARCHAR(64) NOT NULL,
    "BILLING_LAST_NAME" VARCHAR(64) NOT NULL,
    "LATITUDE" VARCHAR(100),
    "LONGITUDE" VARCHAR(100),
    "BILLING_POSTCODE" VARCHAR(20),
    "BILLING_STATE" VARCHAR(100),
    "BILLING_TELEPHONE" VARCHAR(32),
    "CHANNEL" VARCHAR(255),
    "CONFIRMED_ADDRESS" BOOLEAN,
    "CARD_TYPE" VARCHAR(255),
    "CC_CVV" VARCHAR(255),
    "CC_EXPIRES" VARCHAR(255),
    "CC_NUMBER" VARCHAR(255),
    "CC_OWNER" VARCHAR(255),
    "CURRENCY_VALUE" DECIMAL(19, 2),
    "CUSTOMER_AGREED" BOOLEAN,
    "CUSTOMER_EMAIL_ADDRESS" VARCHAR(50) NOT NULL,
    "CUSTOMER_ID" BIGINT,
    "DATE_PURCHASED" DATE,
    "DELIVERY_STREET_ADDRESS" VARCHAR(256),
    "DELIVERY_CITY" VARCHAR(100),
    "DELIVERY_COMPANY" VARCHAR(100),
    "DELIVERY_FIRST_NAME" VARCHAR(64),
    "DELIVERY_LAST_NAME" VARCHAR(64),
    "DELIVERY_POSTCODE" VARCHAR(20),
    "DELIVERY_STATE" VARCHAR(100),
    "DELIVERY_TELEPHONE" VARCHAR(32),
    "IP_ADDRESS" VARCHAR(255),
    "LAST_MODIFIED" TIMESTAMP,
    "LOCALE" VARCHAR(255),
    "ORDER_DATE_FINISHED" TIMESTAMP,
    "ORDER_TYPE" VARCHAR(255),
    "PAYMENT_MODULE_CODE" VARCHAR(255),
    "PAYMENT_TYPE" VARCHAR(255),
    "SHIPPING_MODULE_CODE" VARCHAR(255),
    "ORDER_STATUS" VARCHAR(255),
    "ORDER_TOTAL" DECIMAL(19, 2),
    "BILLING_COUNTRY_ID" INTEGER NOT NULL,
    "BILLING_ZONE_ID" BIGINT,
    "CURRENCY_ID" BIGINT,
    "DELIVERY_COUNTRY_ID" INTEGER,
    "DELIVERY_ZONE_ID" BIGINT,
    "MERCHANTID" INTEGER,
    "CART_CODE" VARCHAR(255)
);     
ALTER TABLE "SALESMANAGER"."ORDERS" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_8B" PRIMARY KEY("ORDER_ID");     
-- 3 +/- SELECT COUNT(*) FROM SALESMANAGER.ORDERS;             
CREATE CACHED TABLE "SALESMANAGER"."CATALOG_ENTRY"(
    "ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "VISIBLE" BOOLEAN,
    "CATALOG_ID" BIGINT NOT NULL,
    "CATEGORY_ID" BIGINT NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL
);          
ALTER TABLE "SALESMANAGER"."CATALOG_ENTRY" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_A6" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CATALOG_ENTRY;      
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_VAR_IMAGE"(
    "PRODUCT_VAR_IMAGE_ID" BIGINT NOT NULL,
    "DEFAULT_IMAGE" BOOLEAN,
    "PRODUCT_IMAGE" VARCHAR(255),
    "PRODUCT_AVAIL_ID" BIGINT NOT NULL
);   
ALTER TABLE "SALESMANAGER"."PRODUCT_VAR_IMAGE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_ADE" PRIMARY KEY("PRODUCT_VAR_IMAGE_ID");             
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_VAR_IMAGE;  
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_VARIATION"(
    "PRODUCT_VARIANTION_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(60),
    "CODE" VARCHAR(100) NOT NULL,
    "MERCHANT_ID" INTEGER NOT NULL,
    "PRODUCT_OPTION_ID" BIGINT NOT NULL,
    "OPTION_VALUE_ID" BIGINT NOT NULL
);           
ALTER TABLE "SALESMANAGER"."PRODUCT_VARIATION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_87E" PRIMARY KEY("PRODUCT_VARIANTION_ID");            
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_VARIATION;  
CREATE CACHED TABLE "SALESMANAGER"."CATALOG"(
    "ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "CODE" VARCHAR(100) NOT NULL,
    "DEFAULT_CATALOG" BOOLEAN,
    "VISIBLE" BOOLEAN,
    "MERCHANT_ID" INTEGER NOT NULL,
    "SORT_ORDER" INTEGER
);        
ALTER TABLE "SALESMANAGER"."CATALOG" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_4B" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.CATALOG;            
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_OPT_SET_PRD_TYPE"(
    "PRODUCTOPTIONSET_PRODUCT_OPTION_SET_ID" BIGINT NOT NULL,
    "PRODUCTTYPES_PRODUCT_TYPE_ID" BIGINT NOT NULL
);             
ALTER TABLE "SALESMANAGER"."PRODUCT_OPT_SET_PRD_TYPE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_8A" PRIMARY KEY("PRODUCTOPTIONSET_PRODUCT_OPTION_SET_ID", "PRODUCTTYPES_PRODUCT_TYPE_ID");     
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_OPT_SET_PRD_TYPE;           
CREATE CACHED TABLE "SALESMANAGER"."AVAILABILITY_VARIATION"(
    "PRODUCT_AVAIL_ID" BIGINT NOT NULL,
    "PRODUCT_VARIANTION_ID" BIGINT NOT NULL
);            
ALTER TABLE "SALESMANAGER"."AVAILABILITY_VARIATION" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_1A" PRIMARY KEY("PRODUCT_AVAIL_ID", "PRODUCT_VARIANTION_ID");    
-- 0 +/- SELECT COUNT(*) FROM SALESMANAGER.AVAILABILITY_VARIATION;             
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_AVAILABILITY"(
    "PRODUCT_AVAIL_ID" BIGINT NOT NULL,
    "DATE_AVAILABLE" DATE,
    "FREE_SHIPPING" BOOLEAN,
    "QUANTITY" INTEGER,
    "QUANTITY_ORD_MAX" INTEGER,
    "QUANTITY_ORD_MIN" INTEGER,
    "STATUS" BOOLEAN,
    "REGION" VARCHAR(255),
    "REGION_VARIANT" VARCHAR(255),
    "PRODUCT_ID" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_MODIFIED" TIMESTAMP,
    "UPDT_ID" VARCHAR(20),
    "AVAILABLE" BOOLEAN,
    "OWNER" VARCHAR(255),
    "MERCHANT_ID" INTEGER,
    "HEIGHT" DECIMAL(19, 2),
    "LENGTH" DECIMAL(19, 2),
    "WEIGHT" DECIMAL(19, 2),
    "WIDTH" DECIMAL(19, 2),
    "SKU" VARCHAR(255)
);    
ALTER TABLE "SALESMANAGER"."PRODUCT_AVAILABILITY" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_63B" PRIMARY KEY("PRODUCT_AVAIL_ID");              
-- 10 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_AVAILABILITY;              
CREATE CACHED TABLE "SALESMANAGER"."PRODUCT_IMAGE"(
    "PRODUCT_IMAGE_ID" BIGINT NOT NULL,
    "DEFAULT_IMAGE" BOOLEAN,
    "IMAGE_CROP" BOOLEAN,
    "IMAGE_TYPE" INTEGER,
    "PRODUCT_IMAGE" VARCHAR(255),
    "PRODUCT_IMAGE_URL" VARCHAR(255),
    "PRODUCT_ID" BIGINT NOT NULL,
    "SORT_ORDER" INTEGER
);             
ALTER TABLE "SALESMANAGER"."PRODUCT_IMAGE" ADD CONSTRAINT "SALESMANAGER"."CONSTRAINT_42" PRIMARY KEY("PRODUCT_IMAGE_ID");      
-- 12 +/- SELECT COUNT(*) FROM SALESMANAGER.PRODUCT_IMAGE;     
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."UK6V48AV32RLI7QU9M3KSB32ART" UNIQUE("MERCHANT_ID", "CUSTOMER_NICK");      
ALTER TABLE "SALESMANAGER"."MANUFACTURER" ADD CONSTRAINT "SALESMANAGER"."UK6BRQFDKGA7JC78N8DH3V595Y3" UNIQUE("MERCHANT_ID", "CODE");           
ALTER TABLE "SALESMANAGER"."CATALOG" ADD CONSTRAINT "SALESMANAGER"."UK32MUBPUBTAQU30N34BWL7XIIS" UNIQUE("MERCHANT_ID", "CODE");
ALTER TABLE "SALESMANAGER"."PRODUCT" ADD CONSTRAINT "SALESMANAGER"."UKS8OFSN9PEHDRSTJG52J5QABXH" UNIQUE("MERCHANT_ID", "SKU"); 
ALTER TABLE "SALESMANAGER"."CURRENCY" ADD CONSTRAINT "SALESMANAGER"."UK_M7KU15EKUD52VP67RY73A36TE" UNIQUE("CURRENCY_CURRENCY_CODE");           
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE" ADD CONSTRAINT "SALESMANAGER"."UKIXBPI4HXRHLJH935C3XFVNVSH" UNIQUE("MERCHANT_ID", "PRODUCT_OPTION_VAL_CODE");
ALTER TABLE "SALESMANAGER"."PRODUCT_REVIEW" ADD CONSTRAINT "SALESMANAGER"."UK9EW5IDGDBK8A77534HBNHD4YB" UNIQUE("CUSTOMERS_ID", "PRODUCT_ID");  
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_SET" ADD CONSTRAINT "SALESMANAGER"."UKK1QQ8J685UJ17BYLGNKRA1N5F" UNIQUE("MERCHANT_ID", "PRODUCT_OPTION_SET_CODE");  
ALTER TABLE "SALESMANAGER"."PRODUCT_PRICE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKFRSW8D41SXXOGVXXOYD8NWAXU" UNIQUE("PRODUCT_PRICE_ID", "LANGUAGE_ID");  
ALTER TABLE "SALESMANAGER"."CONTENT" ADD CONSTRAINT "SALESMANAGER"."UKT1V2LD0MRWVIQUQOURQL4UUB0" UNIQUE("MERCHANT_ID", "CODE");
ALTER TABLE "SALESMANAGER"."CUSTOMER_REVIEW" ADD CONSTRAINT "SALESMANAGER"."UK2MOMTHBFRTGICO2YYOD8W18PK" UNIQUE("CUSTOMERS_ID", "REVIEWED_CUSTOMER_ID");       
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_DESC" ADD CONSTRAINT "SALESMANAGER"."UK6OVL4T1CIAG1WUBTCEBAOO7VI" UNIQUE("CUSTOMER_OPTION_ID", "LANGUAGE_ID");     
ALTER TABLE "SALESMANAGER"."CURRENCY" ADD CONSTRAINT "SALESMANAGER"."UK_1UBR7N96HJAJAMTGGQP090A4X" UNIQUE("CURRENCY_CODE");    
ALTER TABLE "SALESMANAGER"."CUSTOMER_REVIEW_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UK1VA9Q0NHOE3WLI25KTPMOUVYH" UNIQUE("CUSTOMER_REVIEW_ID", "LANGUAGE_ID");              
ALTER TABLE "SALESMANAGER"."PRODUCT_TYPE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKBNRA4LWQJKJU4YH04824SW6BE" UNIQUE("PRODUCT_TYPE_ID", "LANGUAGE_ID");    
ALTER TABLE "SALESMANAGER"."SM_GROUP" ADD CONSTRAINT "SALESMANAGER"."UK_T83RJSOML3O785OJ37LPQPYKO" UNIQUE("GROUP_NAME");       
ALTER TABLE "SALESMANAGER"."TAX_RATE" ADD CONSTRAINT "SALESMANAGER"."UK8GH6L9N0XQ03B91SGLP62OELU" UNIQUE("TAX_CODE", "MERCHANT_ID");           
ALTER TABLE "SALESMANAGER"."TAX_CLASS" ADD CONSTRAINT "SALESMANAGER"."UKA4Q5Q57A8OEH2OJEO8DHR935K" UNIQUE("MERCHANT_ID", "TAX_CLASS_CODE");    
ALTER TABLE "SALESMANAGER"."MERCHANT_STORE" ADD CONSTRAINT "SALESMANAGER"."UK_4PVTSNQV4NLAO8725N9LDPGUF" UNIQUE("STORE_CODE"); 
ALTER TABLE "SALESMANAGER"."GEOZONE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKSOQ8O99W3C8YS3NTAMT5I4MAT" UNIQUE("GEOZONE_ID", "LANGUAGE_ID");              
ALTER TABLE "SALESMANAGER"."USERS" ADD CONSTRAINT "SALESMANAGER"."UKT2HV34K7G4PO0PVMMVT5C7VGO" UNIQUE("MERCHANT_ID", "ADMIN_NAME");            
ALTER TABLE "SALESMANAGER"."PRODUCT_IMAGE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKN7YHDJ6CCYDGF201GIBB882CD" UNIQUE("PRODUCT_IMAGE_ID", "LANGUAGE_ID");  
ALTER TABLE "SALESMANAGER"."USERS" ADD CONSTRAINT "SALESMANAGER"."UK_7RBCJ0GSTOLIJ2MP5G3XC7XFU" UNIQUE("ADMIN_NAME");          
ALTER TABLE "SALESMANAGER"."ZONE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKM64LAXGRV9FXM6IO232AP4SU9" UNIQUE("ZONE_ID", "LANGUAGE_ID");    
ALTER TABLE "SALESMANAGER"."CUSTOMER_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."UK46KBPRE88YH963GEWM3KMDNI1" UNIQUE("OPTION_ID", "CUSTOMER_ID");
ALTER TABLE "SALESMANAGER"."SYSTEM_NOTIFICATION" ADD CONSTRAINT "SALESMANAGER"."UKNPDNLC390VGR2MHEPIB1MTRMR" UNIQUE("MERCHANT_ID", "CONFIG_KEY");              
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION" ADD CONSTRAINT "SALESMANAGER"."UKHFCW5OI9ULLJLOG1B7NS1R9TU" UNIQUE("MERCHANT_ID", "PRODUCT_OPTION_CODE");          
ALTER TABLE "SALESMANAGER"."CATALOG_ENTRY" ADD CONSTRAINT "SALESMANAGER"."UK5Q8159I414R299KIA2W9RE90K" UNIQUE("CATEGORY_ID", "CATALOG_ID");    
ALTER TABLE "SALESMANAGER"."MANUFACTURER_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKLPV09P83SC887CLXE04NROUP6" UNIQUE("MANUFACTURER_ID", "LANGUAGE_ID");    
ALTER TABLE "SALESMANAGER"."USERS" ADD CONSTRAINT "SALESMANAGER"."UK7CWROWCNJLFXPXPDD1OP9YMAB" UNIQUE("MERCHANT_ID", "ADMIN_NAME");            
ALTER TABLE "SALESMANAGER"."PRODUCT_DIGITAL" ADD CONSTRAINT "SALESMANAGER"."UKJUK1QGKH9V5W7GHVB18KRWO8V" UNIQUE("PRODUCT_ID", "FILE_NAME");    
ALTER TABLE "SALESMANAGER"."CURRENCY" ADD CONSTRAINT "SALESMANAGER"."UK_7R1K69CBK5GIEWQR5C9R4V6F" UNIQUE("CURRENCY_NAME");     
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."UKAPR0M3G0LQGDJGTC2M8DMK267" UNIQUE("MERCHANT_ID", "CUSTOMER_EMAIL_ADDRESS");             
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKASGC60OT1WY0UHO96N0J8429P" UNIQUE("PRODUCT_OPTION_VALUE_ID", "LANGUAGE_ID");    
ALTER TABLE "SALESMANAGER"."COUNTRY" ADD CONSTRAINT "SALESMANAGER"."UK_DQB99V22PT27V0TGEQO958E6X" UNIQUE("COUNTRY_ISOCODE");   
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_VALUE" ADD CONSTRAINT "SALESMANAGER"."UKCB1FMV71NRX7M1RLX1FF5QVDT" UNIQUE("MERCHANT_ID", "CUSTOMER_OPT_VAL_CODE"); 
ALTER TABLE "SALESMANAGER"."PRODUCT_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."UKO0C6CFXCFEJWFA2877GFGPUCO" UNIQUE("OPTION_ID", "OPTION_VALUE_ID", "PRODUCT_ID");               
ALTER TABLE "SALESMANAGER"."FILE_HISTORY" ADD CONSTRAINT "SALESMANAGER"."UKAV35SB3V4NXQ8V1N1RKXUFIR" UNIQUE("MERCHANT_ID", "FILE_ID");         
ALTER TABLE "SALESMANAGER"."ZONE" ADD CONSTRAINT "SALESMANAGER"."UK_4TQ3P5W8K4H4EASYF5T3N1JDR" UNIQUE("ZONE_CODE");            
ALTER TABLE "SALESMANAGER"."SHOPPING_CART" ADD CONSTRAINT "SALESMANAGER"."UK_8LD8P40FWRJOBI7T3N95PNA35" UNIQUE("SHP_CART_CODE");               
ALTER TABLE "SALESMANAGER"."CATEGORY_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKBUESQQ6CYX7E5HY3MF30CFIEQ" UNIQUE("CATEGORY_ID", "LANGUAGE_ID");            
ALTER TABLE "SALESMANAGER"."MERCHANT_CONFIGURATION" ADD CONSTRAINT "SALESMANAGER"."UKJ0C3H8ONW3M6HJCR3YYLST9FB" UNIQUE("MERCHANT_ID", "CONFIG_KEY");           
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_SET" ADD CONSTRAINT "SALESMANAGER"."UK4PELI2RITNNQ2XQPYQ188SRM6" UNIQUE("CUSTOMER_OPTION_ID", "CUSTOMER_OPTION_VALUE_ID");         
ALTER TABLE "SALESMANAGER"."PRODUCT_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKQ4DNKX5B776AYQAS2H4RR2D8Q" UNIQUE("PRODUCT_ID", "LANGUAGE_ID");              
ALTER TABLE "SALESMANAGER"."PERMISSION" ADD CONSTRAINT "SALESMANAGER"."UK_SS26HGWETKJ8MS5Y5JN2CO4J3" UNIQUE("PERMISSION_NAME");
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_DESC" ADD CONSTRAINT "SALESMANAGER"."UKMKCM8ISYYYQBJD1YYB8MRPKUW" UNIQUE("PRODUCT_OPTION_ID", "LANGUAGE_ID");       
ALTER TABLE "SALESMANAGER"."PRODUCT_VARIATION" ADD CONSTRAINT "SALESMANAGER"."UKI8SA74FV4IO0SIGMGVQXYPP0D" UNIQUE("MERCHANT_ID", "PRODUCT_OPTION_ID", "OPTION_VALUE_ID");      
ALTER TABLE "SALESMANAGER"."CATEGORY" ADD CONSTRAINT "SALESMANAGER"."UK3MQ9I6QMGQUVOIESLX39PEJ6X" UNIQUE("MERCHANT_ID", "CODE");               
ALTER TABLE "SALESMANAGER"."PRODUCT_REVIEW_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKQNO5WJDTCJ8PM3YKKKH7T4RXJ" UNIQUE("PRODUCT_REVIEW_ID", "LANGUAGE_ID");
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPT_VAL_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKGE7F2T1D31R87WNK09H9U1TNV" UNIQUE("CUSTOMER_OPT_VAL_ID", "LANGUAGE_ID");            
ALTER TABLE "SALESMANAGER"."OPTIN" ADD CONSTRAINT "SALESMANAGER"."UKMANLX6SIQ6DDF14CUD40K8GW6" UNIQUE("MERCHANT_ID", "CODE");  
ALTER TABLE "SALESMANAGER"."CATALOG_ENTRY" ADD CONSTRAINT "SALESMANAGER"."UKENVPF5BRCG399WEJ8E2OQ1QD2" UNIQUE("PRODUCT_ID", "CATEGORY_ID", "CATALOG_ID");      
ALTER TABLE "SALESMANAGER"."CONTENT_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKN0W5R7CTBP88R4RVK7AYKLOFM" UNIQUE("CONTENT_ID", "LANGUAGE_ID");              
ALTER TABLE "SALESMANAGER"."COUNTRY_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKT7NSHKI1RBP6157ED0V6CX4Y4" UNIQUE("COUNTRY_ID", "LANGUAGE_ID");              
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION" ADD CONSTRAINT "SALESMANAGER"."UKROV34A6G4DHHIQUKVHP1GGM0U" UNIQUE("MERCHANT_ID", "CUSTOMER_OPT_CODE");           
ALTER TABLE "SALESMANAGER"."TAX_RATE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."UKT3XG8PL88YACDXG49NB46EFFG" UNIQUE("TAX_RATE_ID", "LANGUAGE_ID");            
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTIN" ADD CONSTRAINT "SALESMANAGER"."UKC4FNYU0PVXXTRBKO10RM1JQYW" UNIQUE("EMAIL", "OPTIN_ID");           
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPT_VAL_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK6RFSSI3QFX4PSWICXRFB18C1" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."PRODUCT_TYPE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK81Q74WHCO5Y9FD51AA330HLC0" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."ZONE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKPV4ELIN6W3B03756OBQVK447F" FOREIGN KEY("ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION" ADD CONSTRAINT "SALESMANAGER"."FKP8CSKI5T5F5M4ET4FW0UILCGU" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_IMAGE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKLHDNPKI4SF98WEV0PCJ2BVNIH" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;     
ALTER TABLE "SALESMANAGER"."PRODUCT_VAR_IMAGE" ADD CONSTRAINT "SALESMANAGER"."FKGGBBYS5MEWFLR88RSOS56YC2K" FOREIGN KEY("PRODUCT_AVAIL_ID") REFERENCES "SALESMANAGER"."PRODUCT_AVAILABILITY"("PRODUCT_AVAIL_ID") NOCHECK;       
ALTER TABLE "SALESMANAGER"."PRODUCT" ADD CONSTRAINT "SALESMANAGER"."FKEIIRVJ8EU40H103FTH8ES1MT0" FOREIGN KEY("PRODUCT_TYPE_ID") REFERENCES "SALESMANAGER"."PRODUCT_TYPE"("PRODUCT_TYPE_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."CUSTOMER_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."FK9FL7IEXVDEEEOCH9FH35O5VW4" FOREIGN KEY("OPTION_VALUE_ID") REFERENCES "SALESMANAGER"."CUSTOMER_OPTION_VALUE"("CUSTOMER_OPTION_VALUE_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."CUSTOMER_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."FK4XUGS9YD9W4O3SW11FISB8TJ5" FOREIGN KEY("OPTION_ID") REFERENCES "SALESMANAGER"."CUSTOMER_OPTION"("CUSTOMER_OPTION_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."TAX_CLASS" ADD CONSTRAINT "SALESMANAGER"."FK82I8PUUJGHCV7FC82QWSGJG8W" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;               
ALTER TABLE "SALESMANAGER"."PRODUCT_AVAILABILITY" ADD CONSTRAINT "SALESMANAGER"."FK5SBH4DX25PMJCQX958HR9YS8H" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;             
ALTER TABLE "SALESMANAGER"."ZONE" ADD CONSTRAINT "SALESMANAGER"."FKHN2C1W3E1TWHJG7TIWV7VUK67" FOREIGN KEY("COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;             
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."FK3K21JW28BBX043C2MNHEVG9W4" FOREIGN KEY("DELIVERY_ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."CONTENT_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK47YXF681U0RFW2KVARHQB0R3V" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."MANUFACTURER" ADD CONSTRAINT "SALESMANAGER"."FKHSWPH4NTHRQWFFJEKCCUDSRT2" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."CUSTOMER_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."FKC3318O13I2BPXKCI1BH52WE5A" FOREIGN KEY("CUSTOMER_ID") REFERENCES "SALESMANAGER"."CUSTOMER"("CUSTOMER_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."PRODUCT_REVIEW_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK7BYC5JSF5BM4LK674AC44E50M" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."CONTENT_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKK7FABFXN2FLVCOFWWPYG5SYS" FOREIGN KEY("CONTENT_ID") REFERENCES "SALESMANAGER"."CONTENT"("CONTENT_ID") NOCHECK;               
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK19MNBY7ATLT85EXLYPXDXHACX" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."CATEGORY" ADD CONSTRAINT "SALESMANAGER"."FK8A09ASQ5FCX0A88I4M8NSIXY" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK; 
ALTER TABLE "SALESMANAGER"."ORDER_PRODUCT" ADD CONSTRAINT "SALESMANAGER"."FKF0SGHMN59S14CXRJTRVKVI5YK" FOREIGN KEY("ORDER_ID") REFERENCES "SALESMANAGER"."ORDERS"("ORDER_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."PERMISSION_GROUP" ADD CONSTRAINT "SALESMANAGER"."FKR7YLUTDGQP1NRLBHJWIT6Y17G" FOREIGN KEY("GROUP_ID") REFERENCES "SALESMANAGER"."SM_GROUP"("GROUP_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."SHIPPING_QUOTE" ADD CONSTRAINT "SALESMANAGER"."FK9VB7TBJL8IVYGDIQW883FEWX7" FOREIGN KEY("DELIVERY_COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_DESC" ADD CONSTRAINT "SALESMANAGER"."FKM4IU7V9DB17WK2A03XQBQDLFA" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."ORDER_TOTAL" ADD CONSTRAINT "SALESMANAGER"."FK1TFVGK5SMM80EFDCC8UOP4HE3" FOREIGN KEY("ORDER_ID") REFERENCES "SALESMANAGER"."ORDERS"("ORDER_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."PRODUCT" ADD CONSTRAINT "SALESMANAGER"."FKRA5MMRDXN3CI86HOD7Q1U3VU9" FOREIGN KEY("MANUFACTURER_ID") REFERENCES "SALESMANAGER"."MANUFACTURER"("MANUFACTURER_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."CATEGORY_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKA58U7D0YDFGREF1IAUX5EFYOV" FOREIGN KEY("CATEGORY_ID") REFERENCES "SALESMANAGER"."CATEGORY"("CATEGORY_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_VARIATION" ADD CONSTRAINT "SALESMANAGER"."FKQLM3C2178NEUE84L5KX51OVOQ" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;       
ALTER TABLE "SALESMANAGER"."MERCHANT_STORE" ADD CONSTRAINT "SALESMANAGER"."FK2GN7VPKD9X832URW7C6JLAWNN" FOREIGN KEY("COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."GEOZONE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKN82TE2YB2ST4HK2QLHL8ILEB9" FOREIGN KEY("GEOZONE_ID") REFERENCES "SALESMANAGER"."GEOZONE"("GEOZONE_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."TAX_RATE" ADD CONSTRAINT "SALESMANAGER"."FKFWP6YKA2QPS9JNA473E6C6YC1" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."ORDER_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."FK4NW5YRTGB4IN6LEVE76BMDNUA" FOREIGN KEY("ORDER_ID") REFERENCES "SALESMANAGER"."ORDERS"("ORDER_ID") NOCHECK;       
ALTER TABLE "SALESMANAGER"."MERCHANT_LANGUAGE" ADD CONSTRAINT "SALESMANAGER"."FKJWY0PJIJH1QMCOIVQ50O2JGEC" FOREIGN KEY("LANGUAGES_LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."PRODUCT_PRICE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKBWXW861IPJSCT606J3DAGDJSF" FOREIGN KEY("PRODUCT_PRICE_ID") REFERENCES "SALESMANAGER"."PRODUCT_PRICE"("PRODUCT_PRICE_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."PRODUCT_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK6ESJDAA6VU2T5VJIN788A8OG6" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."PRODUCT_TYPE" ADD CONSTRAINT "SALESMANAGER"."FKSWKVTAQ4OM2DI6X8CD4M22OFN" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."COUNTRY_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKERSRBJOT9P9NFUKXFD2L27C7T" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_SET" ADD CONSTRAINT "SALESMANAGER"."FKJ9VNVYH6HHHFTJBCSYMGIODM9" FOREIGN KEY("CUSTOMER_OPTION_VALUE_ID") REFERENCES "SALESMANAGER"."CUSTOMER_OPTION_VALUE"("CUSTOMER_OPTION_VALUE_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."FILE_HISTORY" ADD CONSTRAINT "SALESMANAGER"."FK2K8H4PENKJLBTC23VAMWYEK2G" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."PRODUCT_OPT_SET_PRD_TYPE" ADD CONSTRAINT "SALESMANAGER"."FKIEM30U1ENM0P25I7T53JGANF4" FOREIGN KEY("PRODUCTTYPES_PRODUCT_TYPE_ID") REFERENCES "SALESMANAGER"."PRODUCT_TYPE"("PRODUCT_TYPE_ID") NOCHECK;             
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_DESC" ADD CONSTRAINT "SALESMANAGER"."FKC2YIUCJBW0WJHA8WW7A01QFEO" FOREIGN KEY("CUSTOMER_OPTION_ID") REFERENCES "SALESMANAGER"."CUSTOMER_OPTION"("CUSTOMER_OPTION_ID") NOCHECK;     
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_SET" ADD CONSTRAINT "SALESMANAGER"."FK4NJY17416FN86MUOJMTBAV1D0" FOREIGN KEY("PRODUCT_OPTION_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION"("PRODUCT_OPTION_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_SET" ADD CONSTRAINT "SALESMANAGER"."FK8D5VYLMHVMCKMFRAMDEHGWQAU" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."PRODUCT_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKM46YJCU59Q79QROKGGLWQ2OVE" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."PRODUCT_OPT_SET_OPT_VALUE" ADD CONSTRAINT "SALESMANAGER"."FK9DWATBLXWC64A5LA3BB7QNWD8" FOREIGN KEY("VALUES_PRODUCT_OPTION_VALUE_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION_VALUE"("PRODUCT_OPTION_VALUE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_REVIEW_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKMJIVHIGDCXMYTNDLPJUHF4O25" FOREIGN KEY("PRODUCT_REVIEW_ID") REFERENCES "SALESMANAGER"."PRODUCT_REVIEW"("PRODUCT_REVIEW_ID") NOCHECK;  
ALTER TABLE "SALESMANAGER"."SYSTEM_NOTIFICATION" ADD CONSTRAINT "SALESMANAGER"."FKS6QK7L06E0S6M9N04MOMEDGT7" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;     
ALTER TABLE "SALESMANAGER"."PRODUCT_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."FKML3NVEMDJYA159A7669QT1GJD" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."PERMISSION_GROUP" ADD CONSTRAINT "SALESMANAGER"."FK77LY3KHYUU40ODLY02D351S84" FOREIGN KEY("PERMISSION_ID") REFERENCES "SALESMANAGER"."PERMISSION"("PERMISSION_ID") NOCHECK;        
ALTER TABLE "SALESMANAGER"."USERS" ADD CONSTRAINT "SALESMANAGER"."FKTPIO656E5T0CJA7KX7P79RKH6" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."ORDERS" ADD CONSTRAINT "SALESMANAGER"."FKNLX97VJYORUNXGLHY5BIRD06C" FOREIGN KEY("DELIVERY_COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;  
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."FK5PAS8T9MKNK4KKIN55T4V300L" FOREIGN KEY("BILLING_COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK; 
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPT_VAL_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKHWRS6FYQK6VH11YVCFLU42YEF" FOREIGN KEY("CUSTOMER_OPT_VAL_ID") REFERENCES "SALESMANAGER"."CUSTOMER_OPTION_VALUE"("CUSTOMER_OPTION_VALUE_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."ORDER_PRODUCT_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."FK7J86RVWAYSBOK1NUOFRNMHMKX" FOREIGN KEY("ORDER_PRODUCT_ID") REFERENCES "SALESMANAGER"."ORDER_PRODUCT"("ORDER_PRODUCT_ID") NOCHECK;        
ALTER TABLE "SALESMANAGER"."ORDER_ACCOUNT_PRODUCT" ADD CONSTRAINT "SALESMANAGER"."FK7OXC8YGOV7VD2AJT185JHIWTS" FOREIGN KEY("ORDER_ACCOUNT_ID") REFERENCES "SALESMANAGER"."ORDER_ACCOUNT"("ORDER_ACCOUNT_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_CATEGORY" ADD CONSTRAINT "SALESMANAGER"."FKA7245LY271MB0CRLHXWHHPPSQ" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK; 
ALTER TABLE "SALESMANAGER"."CATEGORY_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKL4J5BOTEUTPU1P8F67KYDPNMD" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."FKBXYOOICELI2KO29BUPDYE6JGN" FOREIGN KEY("DELIVERY_COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."TAX_RATE" ADD CONSTRAINT "SALESMANAGER"."FKM9SNPF6O1NB4J1T80NAS8D1IX" FOREIGN KEY("ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;  
ALTER TABLE "SALESMANAGER"."PRODUCT_IMAGE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK1DHLDO18NJ9L2Y6QYMPGUCYNQ" FOREIGN KEY("PRODUCT_IMAGE_ID") REFERENCES "SALESMANAGER"."PRODUCT_IMAGE"("PRODUCT_IMAGE_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."CUSTOMER_REVIEW" ADD CONSTRAINT "SALESMANAGER"."FKAYT6TBXP7D4G1QYG8CRW2N73P" FOREIGN KEY("CUSTOMERS_ID") REFERENCES "SALESMANAGER"."CUSTOMER"("CUSTOMER_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."FKP0XCPA3I2MGDR0KQ43XIIBX40" FOREIGN KEY("BILLING_ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_DIGITAL" ADD CONSTRAINT "SALESMANAGER"."FK47FMB5CG68PWS7K26TXYL1IL6" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;  
ALTER TABLE "SALESMANAGER"."PRODUCT_RELATIONSHIP" ADD CONSTRAINT "SALESMANAGER"."FKSO3CVINYKAC5WDWU1TJGFOTOR" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;             
ALTER TABLE "SALESMANAGER"."SHOPPING_CART_ITEM" ADD CONSTRAINT "SALESMANAGER"."FK2GBIMDWE9UYSD5XADNFL0XQ83" FOREIGN KEY("SHP_CART_ID") REFERENCES "SALESMANAGER"."SHOPPING_CART"("SHP_CART_ID") NOCHECK;       
ALTER TABLE "SALESMANAGER"."SHIPING_ORIGIN" ADD CONSTRAINT "SALESMANAGER"."FKP0DBWSV3SDSP57EX7J5K9B0OQ" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."CONTENT" ADD CONSTRAINT "SALESMANAGER"."FKFMOI0FKJBTFTY3O8FS94T11R1" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK; 
ALTER TABLE "SALESMANAGER"."PRODUCT_TYPE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKREFXR8Q2QWRASLQGUQL31VU34" FOREIGN KEY("PRODUCT_TYPE_ID") REFERENCES "SALESMANAGER"."PRODUCT_PRICE"("PRODUCT_PRICE_ID") NOCHECK;        
ALTER TABLE "SALESMANAGER"."PRODUCT_AVAILABILITY" ADD CONSTRAINT "SALESMANAGER"."FKMJS1XQDSGJI88J5UDUJ83BNTL" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."CUSTOMER_REVIEW" ADD CONSTRAINT "SALESMANAGER"."FK7PMQDK9OD2AF7CL6ALX82FKEK" FOREIGN KEY("REVIEWED_CUSTOMER_ID") REFERENCES "SALESMANAGER"."CUSTOMER"("CUSTOMER_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."ORDER_STATUS_HISTORY" ADD CONSTRAINT "SALESMANAGER"."FKMHGHGF1XY3O0NPSP8XKJ6WYVQ" FOREIGN KEY("ORDER_ID") REFERENCES "SALESMANAGER"."ORDERS"("ORDER_ID") NOCHECK;  
ALTER TABLE "SALESMANAGER"."ORDER_PRODUCT_DOWNLOAD" ADD CONSTRAINT "SALESMANAGER"."FKSTRDA0EWEHARLD63J8PXA2O2R" FOREIGN KEY("ORDER_PRODUCT_ID") REFERENCES "SALESMANAGER"."ORDER_PRODUCT"("ORDER_PRODUCT_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."USER_GROUP" ADD CONSTRAINT "SALESMANAGER"."FK9OP4WV63NONSBY8Y9MYJHTHO" FOREIGN KEY("USER_ID") REFERENCES "SALESMANAGER"."USERS"("USER_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."USERS" ADD CONSTRAINT "SALESMANAGER"."FK2YN065L2N7NW9ROFJS4HWPIJ2" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."AVAILABILITY_VARIATION" ADD CONSTRAINT "SALESMANAGER"."FK2KHSH7GVB4PF291J0OOSNV7FS" FOREIGN KEY("PRODUCT_AVAIL_ID") REFERENCES "SALESMANAGER"."PRODUCT_AVAILABILITY"("PRODUCT_AVAIL_ID") NOCHECK;  
ALTER TABLE "SALESMANAGER"."MERCHANT_LANGUAGE" ADD CONSTRAINT "SALESMANAGER"."FKIISJ0TMOUJV6N3IQMYTVO39KN" FOREIGN KEY("STORES_MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_DESC" ADD CONSTRAINT "SALESMANAGER"."FK8FIWK5O1GBN2R2U8529YAF9XT" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."SHOPPING_CART_ATTR_ITEM" ADD CONSTRAINT "SALESMANAGER"."FKP42TPA623HYO9WW69V0OHB3ER" FOREIGN KEY("SHP_CART_ITEM_ID") REFERENCES "SALESMANAGER"."SHOPPING_CART_ITEM"("SHP_CART_ITEM_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."USER_GROUP" ADD CONSTRAINT "SALESMANAGER"."FKDONP1M2N25UA1465RHICE3QNA" FOREIGN KEY("USER_ID") REFERENCES "SALESMANAGER"."USERS"("USER_ID") NOCHECK;               
ALTER TABLE "SALESMANAGER"."ORDERS" ADD CONSTRAINT "SALESMANAGER"."FKIT6TI99MV5UVUXQSKHURV3Y59" FOREIGN KEY("BILLING_ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."PRODUCT_OPT_SET_OPT_VALUE" ADD CONSTRAINT "SALESMANAGER"."FK3U6IYAG8X8W9TKT7SQCOIBJQ6" FOREIGN KEY("PRODUCTOPTIONSET_PRODUCT_OPTION_SET_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION_SET"("PRODUCT_OPTION_SET_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION" ADD CONSTRAINT "SALESMANAGER"."FKCMQNH0RN2HUKDFOWEAN5TDY8K" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."ORDERS" ADD CONSTRAINT "SALESMANAGER"."FKAODV5FFAYQ8X50Q311O2Y8M1" FOREIGN KEY("MERCHANTID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."PRODUCT" ADD CONSTRAINT "SALESMANAGER"."FKQTT5F0AHT5H7OUGH5RBKKCB33" FOREIGN KEY("CUSTOMER_ID") REFERENCES "SALESMANAGER"."CUSTOMER"("CUSTOMER_ID") NOCHECK;       
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKQTTC6B79YP2S1HYRHG4THAG6S" FOREIGN KEY("PRODUCT_OPTION_VALUE_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION_VALUE"("PRODUCT_OPTION_VALUE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_REVIEW" ADD CONSTRAINT "SALESMANAGER"."FKBFI8DE7KXULTG1VEVQ6JC1HN7" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."MERCHANT_STORE" ADD CONSTRAINT "SALESMANAGER"."FK63HLW9WP1K1X3F5TKE7T2US7S" FOREIGN KEY("CURRENCY_ID") REFERENCES "SALESMANAGER"."CURRENCY"("CURRENCY_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_SET" ADD CONSTRAINT "SALESMANAGER"."FK1Y5QTSUABHPWFT3DYHQRGMTB4" FOREIGN KEY("CUSTOMER_OPTION_ID") REFERENCES "SALESMANAGER"."CUSTOMER_OPTION"("CUSTOMER_OPTION_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."TAX_RATE" ADD CONSTRAINT "SALESMANAGER"."FK6WM34JCWOEMBE1QSMLE2WTWNV" FOREIGN KEY("COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."SHIPING_ORIGIN" ADD CONSTRAINT "SALESMANAGER"."FKPQIG59USQVS9H0DW4LM8RV7YY" FOREIGN KEY("COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."FKDGJQMJ04QT89GMFLOO4OFOJCW" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."USERS" ADD CONSTRAINT "SALESMANAGER"."FK3SH6QXGT118M71TTVKUBGD9Y8" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."COUNTRY_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKKD2SY7Q97WR2AHVYIIQC4TXJI" FOREIGN KEY("COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."MERCHANT_CONFIGURATION" ADD CONSTRAINT "SALESMANAGER"."FKF9BKGF0YSBP5FO9J69SHM0PRI" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;  
ALTER TABLE "SALESMANAGER"."SHIPING_ORIGIN" ADD CONSTRAINT "SALESMANAGER"."FK6K73F1N18KR7MQP708AIWQ047" FOREIGN KEY("ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."TAX_RATE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKSICB2YDX42O04PVLNXW2MLX0W" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."FK3RLEULTG9FN2DXRUEFBB18D5T" FOREIGN KEY("OPTION_VALUE_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION_VALUE"("PRODUCT_OPTION_VALUE_ID") NOCHECK; 
ALTER TABLE "SALESMANAGER"."CUSTOMER_REVIEW_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKHF88OAGF6T62K28AFN8UAIJC7" FOREIGN KEY("CUSTOMER_REVIEW_ID") REFERENCES "SALESMANAGER"."CUSTOMER_REVIEW"("CUSTOMER_REVIEW_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."PRODUCT_VARIATION" ADD CONSTRAINT "SALESMANAGER"."FKY6GAMYVRPDS502PDCQQ4VOYG" FOREIGN KEY("OPTION_VALUE_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION_VALUE"("PRODUCT_OPTION_VALUE_ID") NOCHECK;  
ALTER TABLE "SALESMANAGER"."ORDER_PRODUCT_PRICE" ADD CONSTRAINT "SALESMANAGER"."FKNKUKIQXRIEONYULERCGNH857S" FOREIGN KEY("ORDER_PRODUCT_ID") REFERENCES "SALESMANAGER"."ORDER_PRODUCT"("ORDER_PRODUCT_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."SHIPPING_QUOTE" ADD CONSTRAINT "SALESMANAGER"."FKIIOESP0VL6X4OM1JEAJJ4UY1T" FOREIGN KEY("DELIVERY_ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."SYSTEM_NOTIFICATION" ADD CONSTRAINT "SALESMANAGER"."FKA54891EMCL0FO27A1QK54SLVK" FOREIGN KEY("USER_ID") REFERENCES "SALESMANAGER"."USERS"("USER_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."PRODUCT_PRICE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK7BMBRJR8AR5ICWDPT8MYJ6GEI" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;     
ALTER TABLE "SALESMANAGER"."MERCHANT_STORE" ADD CONSTRAINT "SALESMANAGER"."FK5O24AKY9161JYOFYXMG0G53VV" FOREIGN KEY("ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."PRODUCT_ATTRIBUTE" ADD CONSTRAINT "SALESMANAGER"."FK2ST60U9TWMVVAOWWN88MT3LRX" FOREIGN KEY("OPTION_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION"("PRODUCT_OPTION_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."PRODUCT_VARIATION" ADD CONSTRAINT "SALESMANAGER"."FK5JR2RC6T2P27NWDO5EQWA7658" FOREIGN KEY("PRODUCT_OPTION_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION"("PRODUCT_OPTION_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."TAX_RATE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK65C2LQSLK5KX25DPKEM2R0VXQ" FOREIGN KEY("TAX_RATE_ID") REFERENCES "SALESMANAGER"."TAX_RATE"("TAX_RATE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."CATALOG_ENTRY" ADD CONSTRAINT "SALESMANAGER"."FK374WKS7EM54D0OGHJU0EARTTL" FOREIGN KEY("CATEGORY_ID") REFERENCES "SALESMANAGER"."CATEGORY"("CATEGORY_ID") NOCHECK; 
ALTER TABLE "SALESMANAGER"."MERCHANT_LOG" ADD CONSTRAINT "SALESMANAGER"."FKTO727B9R68QRTN2VVDQDVD4IC" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTIN" ADD CONSTRAINT "SALESMANAGER"."FK7QYM878M07CWVS4FOE68LVQJT" FOREIGN KEY("OPTIN_ID") REFERENCES "SALESMANAGER"."OPTIN"("OPTIN_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."CATALOG_ENTRY" ADD CONSTRAINT "SALESMANAGER"."FKQP2J48HB3VODOVB8GN2O4GOX" FOREIGN KEY("CATALOG_ID") REFERENCES "SALESMANAGER"."CATALOG"("ID") NOCHECK;             
ALTER TABLE "SALESMANAGER"."MANUFACTURER_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKRE4IYS57N5CFBGPG3QQGEWTRH" FOREIGN KEY("MANUFACTURER_ID") REFERENCES "SALESMANAGER"."MANUFACTURER"("MANUFACTURER_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."MERCHANT_STORE" ADD CONSTRAINT "SALESMANAGER"."FKDNEMO9TL8TJHKXKO83PSVKV19" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTION_VALUE" ADD CONSTRAINT "SALESMANAGER"."FKHO87SSG5RNVWAUJ3Y690A96G6" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."AVAILABILITY_VARIATION" ADD CONSTRAINT "SALESMANAGER"."FK1GXEL47P32K4XSNP72OOXD0NE" FOREIGN KEY("PRODUCT_VARIANTION_ID") REFERENCES "SALESMANAGER"."PRODUCT_VARIATION"("PRODUCT_VARIANTION_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."PRODUCT_RELATIONSHIP" ADD CONSTRAINT "SALESMANAGER"."FKNPRVSWTBGRM6BJFQ3CBDL3QSM" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_DESC" ADD CONSTRAINT "SALESMANAGER"."FKGJQMFOFILE4HWV867IRSNVUC0" FOREIGN KEY("PRODUCT_OPTION_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION"("PRODUCT_OPTION_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."PRODUCT_TYPE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FKPWC89ULK7C9ASBP2NFY2T4X2J" FOREIGN KEY("PRODUCT_TYPE_ID") REFERENCES "SALESMANAGER"."PRODUCT_TYPE"("PRODUCT_TYPE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."COUNTRY" ADD CONSTRAINT "SALESMANAGER"."FKD2Q9E14KH1J6TM1GPBCT2XWWS" FOREIGN KEY("GEOZONE_ID") REFERENCES "SALESMANAGER"."GEOZONE"("GEOZONE_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."CATALOG" ADD CONSTRAINT "SALESMANAGER"."FKRANQ0RWEB0R6J31J565AK51G8" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK; 
ALTER TABLE "SALESMANAGER"."PRODUCT_IMAGE" ADD CONSTRAINT "SALESMANAGER"."FKGAB836D8RXQG8VV55NM02R65I" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."USERS" ADD CONSTRAINT "SALESMANAGER"."FK4YB3HO4YXVCJNIQG09OPBM7JA" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."SM_TRANSACTION" ADD CONSTRAINT "SALESMANAGER"."FK7J0S1GQH2TUE1FYH5NYJ5KWKP" FOREIGN KEY("ORDER_ID") REFERENCES "SALESMANAGER"."ORDERS"("ORDER_ID") NOCHECK;        
ALTER TABLE "SALESMANAGER"."USER_GROUP" ADD CONSTRAINT "SALESMANAGER"."FK75KAINRHN4KH8J3SW2XBE7V61" FOREIGN KEY("GROUP_ID") REFERENCES "SALESMANAGER"."SM_GROUP"("GROUP_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."PRODUCT_OPT_SET_PRD_TYPE" ADD CONSTRAINT "SALESMANAGER"."FK4655H91S0EIINONAKO9N4H9HA" FOREIGN KEY("PRODUCTOPTIONSET_PRODUCT_OPTION_SET_ID") REFERENCES "SALESMANAGER"."PRODUCT_OPTION_SET"("PRODUCT_OPTION_SET_ID") NOCHECK;       
ALTER TABLE "SALESMANAGER"."CUSTOMER_OPTIN" ADD CONSTRAINT "SALESMANAGER"."FKK5V94DVHSGIBAW89HV4M8O5YW" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."TAX_RATE" ADD CONSTRAINT "SALESMANAGER"."FK7BPA9PBL1GNJ5Y3XBGS3WC0EG" FOREIGN KEY("TAX_CLASS_ID") REFERENCES "SALESMANAGER"."TAX_CLASS"("TAX_CLASS_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."MANUFACTURER_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK20T33WR4TP1KT1UYW7S8A3AFL" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."CUSTOMER_GROUP" ADD CONSTRAINT "SALESMANAGER"."FKGRR5V89L1M9SL2QOL62BBCTQ4" FOREIGN KEY("GROUP_ID") REFERENCES "SALESMANAGER"."SM_GROUP"("GROUP_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."ZONE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK69YBU7R3BGPCQ65C77JI1UDH3" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."ORDERS" ADD CONSTRAINT "SALESMANAGER"."FKN9UVJL8105FSLY4DOO8RQNV5B" FOREIGN KEY("DELIVERY_ZONE_ID") REFERENCES "SALESMANAGER"."ZONE"("ZONE_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."CATEGORY" ADD CONSTRAINT "SALESMANAGER"."FKN3KEKNTR7PM8G9V8ASK698ATO" FOREIGN KEY("PARENT_ID") REFERENCES "SALESMANAGER"."CATEGORY"("CATEGORY_ID") NOCHECK;        
ALTER TABLE "SALESMANAGER"."GEOZONE_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK1T2HP628EDEBE5D6CO2WHBLA9" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."PRODUCT_CATEGORY" ADD CONSTRAINT "SALESMANAGER"."FK3XW1SBAA29R534JVEDIMDD7MD" FOREIGN KEY("CATEGORY_ID") REFERENCES "SALESMANAGER"."CATEGORY"("CATEGORY_ID") NOCHECK;              
ALTER TABLE "SALESMANAGER"."ORDERS" ADD CONSTRAINT "SALESMANAGER"."FKFUSIVMW6Q3GJXNMP47N9S74QI" FOREIGN KEY("CURRENCY_ID") REFERENCES "SALESMANAGER"."CURRENCY"("CURRENCY_ID") NOCHECK;        
ALTER TABLE "SALESMANAGER"."PRODUCT_VARIANT" ADD CONSTRAINT "SALESMANAGER"."FKNAA1T3G2D6LT3F13YY0GG9T4O" FOREIGN KEY("PRODUCT_AVAIL_ID") REFERENCES "SALESMANAGER"."PRODUCT_AVAILABILITY"("PRODUCT_AVAIL_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."PRODUCT_VARIANT" ADD CONSTRAINT "SALESMANAGER"."FKB1P1MGAA76XDQMX029CABGC1S" FOREIGN KEY("PRODUCT_ATTRIBUTE_ID") REFERENCES "SALESMANAGER"."PRODUCT_ATTRIBUTE"("PRODUCT_ATTRIBUTE_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."ORDER_ACCOUNT_PRODUCT" ADD CONSTRAINT "SALESMANAGER"."FK5KIYYB8EKQI9BFOWYTWW8ATCX" FOREIGN KEY("ORDER_PRODUCT_ID") REFERENCES "SALESMANAGER"."ORDER_PRODUCT"("ORDER_PRODUCT_ID") NOCHECK;          
ALTER TABLE "SALESMANAGER"."CUSTOMER" ADD CONSTRAINT "SALESMANAGER"."FK8122NRPAKXU3UMK1OD4V0XXOA" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."CUSTOMER_GROUP" ADD CONSTRAINT "SALESMANAGER"."FK257H3E27F4UJW08DOQTQ46HHO" FOREIGN KEY("CUSTOMER_ID") REFERENCES "SALESMANAGER"."CUSTOMER"("CUSTOMER_ID") NOCHECK;
ALTER TABLE "SALESMANAGER"."PRODUCT_RELATIONSHIP" ADD CONSTRAINT "SALESMANAGER"."FKFSKWTAWYT85G9H6761FA69YA5" FOREIGN KEY("RELATED_PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;     
ALTER TABLE "SALESMANAGER"."SYSTEM_NOTIFICATION" ADD CONSTRAINT "SALESMANAGER"."FK3DYKR9PM9LN1UEKTUW18BLB6M" FOREIGN KEY("USER_ID") REFERENCES "SALESMANAGER"."USERS"("USER_ID") NOCHECK;      
ALTER TABLE "SALESMANAGER"."PRODUCT" ADD CONSTRAINT "SALESMANAGER"."FKHHOQ1ND9E0I4M7RT8GKH7D67H" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK; 
ALTER TABLE "SALESMANAGER"."SHOPPING_CART" ADD CONSTRAINT "SALESMANAGER"."FKQVGHR5RMJEFE3LW9MCOLK30A0" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."OPTIN" ADD CONSTRAINT "SALESMANAGER"."FK37XVFO4THE20AVV7F1E1771FH" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."PRODUCT_OPTION_VALUE" ADD CONSTRAINT "SALESMANAGER"."FKND3NW0MAMLK8BKXO8AD5M85PQ" FOREIGN KEY("MERCHANT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."PRODUCT_REVIEW" ADD CONSTRAINT "SALESMANAGER"."FK7TM0JRT0HIUGO3EP49T3SUBOU" FOREIGN KEY("CUSTOMERS_ID") REFERENCES "SALESMANAGER"."CUSTOMER"("CUSTOMER_ID") NOCHECK;               
ALTER TABLE "SALESMANAGER"."CUSTOMER_REVIEW_DESCRIPTION" ADD CONSTRAINT "SALESMANAGER"."FK5PKGRLK32UQAXKRBVE5MWS1HJ" FOREIGN KEY("LANGUAGE_ID") REFERENCES "SALESMANAGER"."LANGUAGE"("LANGUAGE_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."ORDER_ACCOUNT" ADD CONSTRAINT "SALESMANAGER"."FKI6L5ISODH81M5HY8UA06HX73N" FOREIGN KEY("ORDER_ID") REFERENCES "SALESMANAGER"."ORDERS"("ORDER_ID") NOCHECK;         
ALTER TABLE "SALESMANAGER"."ORDERS" ADD CONSTRAINT "SALESMANAGER"."FKIPESU5TUPNRIAHUTGLE6XU9ED" FOREIGN KEY("BILLING_COUNTRY_ID") REFERENCES "SALESMANAGER"."COUNTRY"("COUNTRY_ID") NOCHECK;   
ALTER TABLE "SALESMANAGER"."CATALOG_ENTRY" ADD CONSTRAINT "SALESMANAGER"."FK4E5UGD4JLC0N6I4OHRVA71ANV" FOREIGN KEY("PRODUCT_ID") REFERENCES "SALESMANAGER"."PRODUCT"("PRODUCT_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."PRODUCT_PRICE" ADD CONSTRAINT "SALESMANAGER"."FK1DIC7JNNK1QIKGVWCRF4DW12R" FOREIGN KEY("PRODUCT_AVAIL_ID") REFERENCES "SALESMANAGER"."PRODUCT_AVAILABILITY"("PRODUCT_AVAIL_ID") NOCHECK;           
ALTER TABLE "SALESMANAGER"."PRODUCT" ADD CONSTRAINT "SALESMANAGER"."FKB8OQTC3J8SQO0T8XDRNE7PG69" FOREIGN KEY("TAX_CLASS_ID") REFERENCES "SALESMANAGER"."TAX_CLASS"("TAX_CLASS_ID") NOCHECK;    
ALTER TABLE "SALESMANAGER"."MERCHANT_STORE" ADD CONSTRAINT "SALESMANAGER"."FKGKOELE515H76U39B9DEFIBKM9" FOREIGN KEY("PARENT_ID") REFERENCES "SALESMANAGER"."MERCHANT_STORE"("MERCHANT_ID") NOCHECK;            
ALTER TABLE "SALESMANAGER"."TAX_RATE" ADD CONSTRAINT "SALESMANAGER"."FKT8ISEN27I3IOA0TW3BL8QLVDH" FOREIGN KEY("PARENT_ID") REFERENCES "SALESMANAGER"."TAX_RATE"("TAX_RATE_ID") NOCHECK;        
